apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-service
  labels:
    app: cosmic-void
    component: stats-service
spec:
  selector:
    matchLabels:
      app: cosmic-void
      component: stats-service
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cosmic-void
        component: stats-service
    spec:
      containers:
      - name: stats-service
        image: us-central1-docker.pkg.dev/project-b6e8596f-fe1e-4dca-a7a/cosmic-void/stats-service:v1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          tcpSocket:
            port: 7011
          initialDelaySeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: TZ
          value: "Asia/Taipei"
        envFrom:
        - configMapRef:
            name: stats-service-config
        - secretRef:
            name: stats-service-secrets
        ports:
        - containerPort: 7011
          name: grpc
      restartPolicy: Always
