apiVersion: v1
kind: Service
metadata:
  name: stats-service
  labels:
    app: cosmic-void
    component: stats-service
spec:
  type: ClusterIP
  selector:
    app: cosmic-void
    component: stats-service
  ports:
  - name: grpc
    port: 7011
    targetPort: grpc
    protocol: TCP
