// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: api/proto/items/items.proto

package items

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ItemsService_ListItemTemplates_FullMethodName           = "/items.ItemsService/ListItemTemplates"
	ItemsService_ListItemTypes_FullMethodName               = "/items.ItemsService/ListItemTypes"
	ItemsService_ListItemRarities_FullMethodName            = "/items.ItemsService/ListItemRarities"
	ItemsService_CreateWeapon_FullMethodName                = "/items.ItemsService/CreateWeapon"
	ItemsService_GetWeaponWithTemplateByID_FullMethodName   = "/items.ItemsService/GetWeaponWithTemplateByID"
	ItemsService_ListWeaponsWithTemplate_FullMethodName     = "/items.ItemsService/ListWeaponsWithTemplate"
	ItemsService_ListArmorsWithTemplate_FullMethodName      = "/items.ItemsService/ListArmorsWithTemplate"
	ItemsService_ListConsumablesWithTemplate_FullMethodName = "/items.ItemsService/ListConsumablesWithTemplate"
	ItemsService_CreateItemTemplate_FullMethodName          = "/items.ItemsService/CreateItemTemplate"
	ItemsService_CreateCompleteWeapon_FullMethodName        = "/items.ItemsService/CreateCompleteWeapon"
	ItemsService_CreateCompleteArmor_FullMethodName         = "/items.ItemsService/CreateCompleteArmor"
	ItemsService_CreateCompleteConsumable_FullMethodName    = "/items.ItemsService/CreateCompleteConsumable"
	ItemsService_GetLoadout_FullMethodName                  = "/items.ItemsService/GetLoadout"
	ItemsService_GetLoadoutWithItems_FullMethodName         = "/items.ItemsService/GetLoadoutWithItems"
	ItemsService_ListItemInstances_FullMethodName           = "/items.ItemsService/ListItemInstances"
	ItemsService_UpdateLoadout_FullMethodName               = "/items.ItemsService/UpdateLoadout"
)

// ItemsServiceClient is the client API for ItemsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ItemsService external API for items
type ItemsServiceClient interface {
	// general
	ListItemTemplates(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListItemTemplatesResponse, error)
	// ItemType operations (for dropdown/select options)
	ListItemTypes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListItemTypesResponse, error)
	// ItemRarity operations (for dropdown/select options)
	ListItemRarities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListItemRaritiesResponse, error)
	// Weapon operations
	CreateWeapon(ctx context.Context, in *CreateWeaponRequest, opts ...grpc.CallOption) (*Weapon, error)
	GetWeaponWithTemplateByID(ctx context.Context, in *GetWeaponRequest, opts ...grpc.CallOption) (*WeaponDetail, error)
	ListWeaponsWithTemplate(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListWeaponsResponse, error)
	// Armor operations
	ListArmorsWithTemplate(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListArmorsResponse, error)
	// Consumable operations
	ListConsumablesWithTemplate(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListConsumablesResponse, error)
	// ItemTemplate operations
	CreateItemTemplate(ctx context.Context, in *CreateItemTemplateRequest, opts ...grpc.CallOption) (*ItemTemplate, error)
	// Complete item operations (creates both specific item + template)
	CreateCompleteWeapon(ctx context.Context, in *CreateCompleteWeaponRequest, opts ...grpc.CallOption) (*WeaponDetail, error)
	CreateCompleteArmor(ctx context.Context, in *CreateCompleteArmorRequest, opts ...grpc.CallOption) (*ArmorDetail, error)
	CreateCompleteConsumable(ctx context.Context, in *CreateCompleteConsumableRequest, opts ...grpc.CallOption) (*ConsumableDetail, error)
	GetLoadout(ctx context.Context, in *GetLoadoutRequest, opts ...grpc.CallOption) (*GetLoadoutResponse, error)
	GetLoadoutWithItems(ctx context.Context, in *GetLoadoutWithItemsRequest, opts ...grpc.CallOption) (*GetLoadoutWithItemsResponse, error)
	ListItemInstances(ctx context.Context, in *ListItemInstancesRequest, opts ...grpc.CallOption) (*ListItemInstancesResponse, error)
	UpdateLoadout(ctx context.Context, in *UpdateLoadoutRequest, opts ...grpc.CallOption) (*UpdateLoadoutResponse, error)
}

type itemsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewItemsServiceClient(cc grpc.ClientConnInterface) ItemsServiceClient {
	return &itemsServiceClient{cc}
}

func (c *itemsServiceClient) ListItemTemplates(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListItemTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListItemTemplatesResponse)
	err := c.cc.Invoke(ctx, ItemsService_ListItemTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemsServiceClient) ListItemTypes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListItemTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListItemTypesResponse)
	err := c.cc.Invoke(ctx, ItemsService_ListItemTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemsServiceClient) ListItemRarities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListItemRaritiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListItemRaritiesResponse)
	err := c.cc.Invoke(ctx, ItemsService_ListItemRarities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemsServiceClient) CreateWeapon(ctx context.Context, in *CreateWeaponRequest, opts ...grpc.CallOption) (*Weapon, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Weapon)
	err := c.cc.Invoke(ctx, ItemsService_CreateWeapon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemsServiceClient) GetWeaponWithTemplateByID(ctx context.Context, in *GetWeaponRequest, opts ...grpc.CallOption) (*WeaponDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WeaponDetail)
	err := c.cc.Invoke(ctx, ItemsService_GetWeaponWithTemplateByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemsServiceClient) ListWeaponsWithTemplate(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListWeaponsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWeaponsResponse)
	err := c.cc.Invoke(ctx, ItemsService_ListWeaponsWithTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemsServiceClient) ListArmorsWithTemplate(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListArmorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArmorsResponse)
	err := c.cc.Invoke(ctx, ItemsService_ListArmorsWithTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemsServiceClient) ListConsumablesWithTemplate(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListConsumablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConsumablesResponse)
	err := c.cc.Invoke(ctx, ItemsService_ListConsumablesWithTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemsServiceClient) CreateItemTemplate(ctx context.Context, in *CreateItemTemplateRequest, opts ...grpc.CallOption) (*ItemTemplate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemTemplate)
	err := c.cc.Invoke(ctx, ItemsService_CreateItemTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemsServiceClient) CreateCompleteWeapon(ctx context.Context, in *CreateCompleteWeaponRequest, opts ...grpc.CallOption) (*WeaponDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WeaponDetail)
	err := c.cc.Invoke(ctx, ItemsService_CreateCompleteWeapon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemsServiceClient) CreateCompleteArmor(ctx context.Context, in *CreateCompleteArmorRequest, opts ...grpc.CallOption) (*ArmorDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArmorDetail)
	err := c.cc.Invoke(ctx, ItemsService_CreateCompleteArmor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemsServiceClient) CreateCompleteConsumable(ctx context.Context, in *CreateCompleteConsumableRequest, opts ...grpc.CallOption) (*ConsumableDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsumableDetail)
	err := c.cc.Invoke(ctx, ItemsService_CreateCompleteConsumable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemsServiceClient) GetLoadout(ctx context.Context, in *GetLoadoutRequest, opts ...grpc.CallOption) (*GetLoadoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLoadoutResponse)
	err := c.cc.Invoke(ctx, ItemsService_GetLoadout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemsServiceClient) GetLoadoutWithItems(ctx context.Context, in *GetLoadoutWithItemsRequest, opts ...grpc.CallOption) (*GetLoadoutWithItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLoadoutWithItemsResponse)
	err := c.cc.Invoke(ctx, ItemsService_GetLoadoutWithItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemsServiceClient) ListItemInstances(ctx context.Context, in *ListItemInstancesRequest, opts ...grpc.CallOption) (*ListItemInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListItemInstancesResponse)
	err := c.cc.Invoke(ctx, ItemsService_ListItemInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemsServiceClient) UpdateLoadout(ctx context.Context, in *UpdateLoadoutRequest, opts ...grpc.CallOption) (*UpdateLoadoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLoadoutResponse)
	err := c.cc.Invoke(ctx, ItemsService_UpdateLoadout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemsServiceServer is the server API for ItemsService service.
// All implementations must embed UnimplementedItemsServiceServer
// for forward compatibility.
//
// ItemsService external API for items
type ItemsServiceServer interface {
	// general
	ListItemTemplates(context.Context, *emptypb.Empty) (*ListItemTemplatesResponse, error)
	// ItemType operations (for dropdown/select options)
	ListItemTypes(context.Context, *emptypb.Empty) (*ListItemTypesResponse, error)
	// ItemRarity operations (for dropdown/select options)
	ListItemRarities(context.Context, *emptypb.Empty) (*ListItemRaritiesResponse, error)
	// Weapon operations
	CreateWeapon(context.Context, *CreateWeaponRequest) (*Weapon, error)
	GetWeaponWithTemplateByID(context.Context, *GetWeaponRequest) (*WeaponDetail, error)
	ListWeaponsWithTemplate(context.Context, *emptypb.Empty) (*ListWeaponsResponse, error)
	// Armor operations
	ListArmorsWithTemplate(context.Context, *emptypb.Empty) (*ListArmorsResponse, error)
	// Consumable operations
	ListConsumablesWithTemplate(context.Context, *emptypb.Empty) (*ListConsumablesResponse, error)
	// ItemTemplate operations
	CreateItemTemplate(context.Context, *CreateItemTemplateRequest) (*ItemTemplate, error)
	// Complete item operations (creates both specific item + template)
	CreateCompleteWeapon(context.Context, *CreateCompleteWeaponRequest) (*WeaponDetail, error)
	CreateCompleteArmor(context.Context, *CreateCompleteArmorRequest) (*ArmorDetail, error)
	CreateCompleteConsumable(context.Context, *CreateCompleteConsumableRequest) (*ConsumableDetail, error)
	GetLoadout(context.Context, *GetLoadoutRequest) (*GetLoadoutResponse, error)
	GetLoadoutWithItems(context.Context, *GetLoadoutWithItemsRequest) (*GetLoadoutWithItemsResponse, error)
	ListItemInstances(context.Context, *ListItemInstancesRequest) (*ListItemInstancesResponse, error)
	UpdateLoadout(context.Context, *UpdateLoadoutRequest) (*UpdateLoadoutResponse, error)
	mustEmbedUnimplementedItemsServiceServer()
}

// UnimplementedItemsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedItemsServiceServer struct{}

func (UnimplementedItemsServiceServer) ListItemTemplates(context.Context, *emptypb.Empty) (*ListItemTemplatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListItemTemplates not implemented")
}
func (UnimplementedItemsServiceServer) ListItemTypes(context.Context, *emptypb.Empty) (*ListItemTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListItemTypes not implemented")
}
func (UnimplementedItemsServiceServer) ListItemRarities(context.Context, *emptypb.Empty) (*ListItemRaritiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListItemRarities not implemented")
}
func (UnimplementedItemsServiceServer) CreateWeapon(context.Context, *CreateWeaponRequest) (*Weapon, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWeapon not implemented")
}
func (UnimplementedItemsServiceServer) GetWeaponWithTemplateByID(context.Context, *GetWeaponRequest) (*WeaponDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWeaponWithTemplateByID not implemented")
}
func (UnimplementedItemsServiceServer) ListWeaponsWithTemplate(context.Context, *emptypb.Empty) (*ListWeaponsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWeaponsWithTemplate not implemented")
}
func (UnimplementedItemsServiceServer) ListArmorsWithTemplate(context.Context, *emptypb.Empty) (*ListArmorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListArmorsWithTemplate not implemented")
}
func (UnimplementedItemsServiceServer) ListConsumablesWithTemplate(context.Context, *emptypb.Empty) (*ListConsumablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConsumablesWithTemplate not implemented")
}
func (UnimplementedItemsServiceServer) CreateItemTemplate(context.Context, *CreateItemTemplateRequest) (*ItemTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateItemTemplate not implemented")
}
func (UnimplementedItemsServiceServer) CreateCompleteWeapon(context.Context, *CreateCompleteWeaponRequest) (*WeaponDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCompleteWeapon not implemented")
}
func (UnimplementedItemsServiceServer) CreateCompleteArmor(context.Context, *CreateCompleteArmorRequest) (*ArmorDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCompleteArmor not implemented")
}
func (UnimplementedItemsServiceServer) CreateCompleteConsumable(context.Context, *CreateCompleteConsumableRequest) (*ConsumableDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCompleteConsumable not implemented")
}
func (UnimplementedItemsServiceServer) GetLoadout(context.Context, *GetLoadoutRequest) (*GetLoadoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLoadout not implemented")
}
func (UnimplementedItemsServiceServer) GetLoadoutWithItems(context.Context, *GetLoadoutWithItemsRequest) (*GetLoadoutWithItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLoadoutWithItems not implemented")
}
func (UnimplementedItemsServiceServer) ListItemInstances(context.Context, *ListItemInstancesRequest) (*ListItemInstancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListItemInstances not implemented")
}
func (UnimplementedItemsServiceServer) UpdateLoadout(context.Context, *UpdateLoadoutRequest) (*UpdateLoadoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLoadout not implemented")
}
func (UnimplementedItemsServiceServer) mustEmbedUnimplementedItemsServiceServer() {}
func (UnimplementedItemsServiceServer) testEmbeddedByValue()                      {}

// UnsafeItemsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ItemsServiceServer will
// result in compilation errors.
type UnsafeItemsServiceServer interface {
	mustEmbedUnimplementedItemsServiceServer()
}

func RegisterItemsServiceServer(s grpc.ServiceRegistrar, srv ItemsServiceServer) {
	// If the following call pancis, it indicates UnimplementedItemsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ItemsService_ServiceDesc, srv)
}

func _ItemsService_ListItemTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServiceServer).ListItemTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemsService_ListItemTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServiceServer).ListItemTemplates(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemsService_ListItemTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServiceServer).ListItemTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemsService_ListItemTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServiceServer).ListItemTypes(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemsService_ListItemRarities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServiceServer).ListItemRarities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemsService_ListItemRarities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServiceServer).ListItemRarities(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemsService_CreateWeapon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWeaponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServiceServer).CreateWeapon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemsService_CreateWeapon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServiceServer).CreateWeapon(ctx, req.(*CreateWeaponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemsService_GetWeaponWithTemplateByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeaponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServiceServer).GetWeaponWithTemplateByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemsService_GetWeaponWithTemplateByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServiceServer).GetWeaponWithTemplateByID(ctx, req.(*GetWeaponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemsService_ListWeaponsWithTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServiceServer).ListWeaponsWithTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemsService_ListWeaponsWithTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServiceServer).ListWeaponsWithTemplate(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemsService_ListArmorsWithTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServiceServer).ListArmorsWithTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemsService_ListArmorsWithTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServiceServer).ListArmorsWithTemplate(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemsService_ListConsumablesWithTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServiceServer).ListConsumablesWithTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemsService_ListConsumablesWithTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServiceServer).ListConsumablesWithTemplate(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemsService_CreateItemTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServiceServer).CreateItemTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemsService_CreateItemTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServiceServer).CreateItemTemplate(ctx, req.(*CreateItemTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemsService_CreateCompleteWeapon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCompleteWeaponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServiceServer).CreateCompleteWeapon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemsService_CreateCompleteWeapon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServiceServer).CreateCompleteWeapon(ctx, req.(*CreateCompleteWeaponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemsService_CreateCompleteArmor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCompleteArmorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServiceServer).CreateCompleteArmor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemsService_CreateCompleteArmor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServiceServer).CreateCompleteArmor(ctx, req.(*CreateCompleteArmorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemsService_CreateCompleteConsumable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCompleteConsumableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServiceServer).CreateCompleteConsumable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemsService_CreateCompleteConsumable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServiceServer).CreateCompleteConsumable(ctx, req.(*CreateCompleteConsumableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemsService_GetLoadout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoadoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServiceServer).GetLoadout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemsService_GetLoadout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServiceServer).GetLoadout(ctx, req.(*GetLoadoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemsService_GetLoadoutWithItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoadoutWithItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServiceServer).GetLoadoutWithItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemsService_GetLoadoutWithItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServiceServer).GetLoadoutWithItems(ctx, req.(*GetLoadoutWithItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemsService_ListItemInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServiceServer).ListItemInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemsService_ListItemInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServiceServer).ListItemInstances(ctx, req.(*ListItemInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemsService_UpdateLoadout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLoadoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServiceServer).UpdateLoadout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemsService_UpdateLoadout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServiceServer).UpdateLoadout(ctx, req.(*UpdateLoadoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ItemsService_ServiceDesc is the grpc.ServiceDesc for ItemsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ItemsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "items.ItemsService",
	HandlerType: (*ItemsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListItemTemplates",
			Handler:    _ItemsService_ListItemTemplates_Handler,
		},
		{
			MethodName: "ListItemTypes",
			Handler:    _ItemsService_ListItemTypes_Handler,
		},
		{
			MethodName: "ListItemRarities",
			Handler:    _ItemsService_ListItemRarities_Handler,
		},
		{
			MethodName: "CreateWeapon",
			Handler:    _ItemsService_CreateWeapon_Handler,
		},
		{
			MethodName: "GetWeaponWithTemplateByID",
			Handler:    _ItemsService_GetWeaponWithTemplateByID_Handler,
		},
		{
			MethodName: "ListWeaponsWithTemplate",
			Handler:    _ItemsService_ListWeaponsWithTemplate_Handler,
		},
		{
			MethodName: "ListArmorsWithTemplate",
			Handler:    _ItemsService_ListArmorsWithTemplate_Handler,
		},
		{
			MethodName: "ListConsumablesWithTemplate",
			Handler:    _ItemsService_ListConsumablesWithTemplate_Handler,
		},
		{
			MethodName: "CreateItemTemplate",
			Handler:    _ItemsService_CreateItemTemplate_Handler,
		},
		{
			MethodName: "CreateCompleteWeapon",
			Handler:    _ItemsService_CreateCompleteWeapon_Handler,
		},
		{
			MethodName: "CreateCompleteArmor",
			Handler:    _ItemsService_CreateCompleteArmor_Handler,
		},
		{
			MethodName: "CreateCompleteConsumable",
			Handler:    _ItemsService_CreateCompleteConsumable_Handler,
		},
		{
			MethodName: "GetLoadout",
			Handler:    _ItemsService_GetLoadout_Handler,
		},
		{
			MethodName: "GetLoadoutWithItems",
			Handler:    _ItemsService_GetLoadoutWithItems_Handler,
		},
		{
			MethodName: "ListItemInstances",
			Handler:    _ItemsService_ListItemInstances_Handler,
		},
		{
			MethodName: "UpdateLoadout",
			Handler:    _ItemsService_UpdateLoadout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/items/items.proto",
}
