// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/proto/items/items.proto

package items

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Layer 1: Basic Weapon (weapons table only - for create/simple queries)
type Weapon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeId        string                 `protobuf:"bytes,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	RarityId      string                 `protobuf:"bytes,3,opt,name=rarity_id,json=rarityId,proto3" json:"rarity_id,omitempty"`
	AttackPower   int32                  `protobuf:"varint,4,opt,name=attack_power,json=attackPower,proto3" json:"attack_power,omitempty"`
	Durability    int32                  `protobuf:"varint,5,opt,name=durability,proto3" json:"durability,omitempty"`
	CriticalRate  float32                `protobuf:"fixed32,6,opt,name=critical_rate,json=criticalRate,proto3" json:"critical_rate,omitempty"`
	WeaponType    string                 `protobuf:"bytes,7,opt,name=weapon_type,json=weaponType,proto3" json:"weapon_type,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weapon) Reset() {
	*x = Weapon{}
	mi := &file_api_proto_items_items_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weapon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weapon) ProtoMessage() {}

func (x *Weapon) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_items_items_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weapon.ProtoReflect.Descriptor instead.
func (*Weapon) Descriptor() ([]byte, []int) {
	return file_api_proto_items_items_proto_rawDescGZIP(), []int{0}
}

func (x *Weapon) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Weapon) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *Weapon) GetRarityId() string {
	if x != nil {
		return x.RarityId
	}
	return ""
}

func (x *Weapon) GetAttackPower() int32 {
	if x != nil {
		return x.AttackPower
	}
	return 0
}

func (x *Weapon) GetDurability() int32 {
	if x != nil {
		return x.Durability
	}
	return 0
}

func (x *Weapon) GetCriticalRate() float32 {
	if x != nil {
		return x.CriticalRate
	}
	return 0
}

func (x *Weapon) GetWeaponType() string {
	if x != nil {
		return x.WeaponType
	}
	return ""
}

func (x *Weapon) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Weapon) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Weapon) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Layer 2: WeaponDetail (weapons + item_templates joined - for detailed queries)
type WeaponDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Weapon specific fields (from weapons table)
	Id           string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeId       string  `protobuf:"bytes,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	RarityId     string  `protobuf:"bytes,3,opt,name=rarity_id,json=rarityId,proto3" json:"rarity_id,omitempty"`
	AttackPower  int32   `protobuf:"varint,4,opt,name=attack_power,json=attackPower,proto3" json:"attack_power,omitempty"`
	Durability   int32   `protobuf:"varint,5,opt,name=durability,proto3" json:"durability,omitempty"`
	CriticalRate float32 `protobuf:"fixed32,6,opt,name=critical_rate,json=criticalRate,proto3" json:"critical_rate,omitempty"`
	WeaponType   string  `protobuf:"bytes,7,opt,name=weapon_type,json=weaponType,proto3" json:"weapon_type,omitempty"`
	Description  string  `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	// ItemTemplate fields (from item_templates table)
	ItemTemplateId string                 `protobuf:"bytes,9,opt,name=item_template_id,json=itemTemplateId,proto3" json:"item_template_id,omitempty"`
	ItemName       string                 `protobuf:"bytes,10,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	ItemCode       string                 `protobuf:"bytes,11,opt,name=item_code,json=itemCode,proto3" json:"item_code,omitempty"`
	IconUrl        string                 `protobuf:"bytes,12,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	IsTradeable    bool                   `protobuf:"varint,13,opt,name=is_tradeable,json=isTradeable,proto3" json:"is_tradeable,omitempty"`
	IsDroppable    bool                   `protobuf:"varint,14,opt,name=is_droppable,json=isDroppable,proto3" json:"is_droppable,omitempty"`
	RequiredLevel  int32                  `protobuf:"varint,15,opt,name=required_level,json=requiredLevel,proto3" json:"required_level,omitempty"`
	BaseSellPrice  int32                  `protobuf:"varint,16,opt,name=base_sell_price,json=baseSellPrice,proto3" json:"base_sell_price,omitempty"`
	BaseBuyPrice   int32                  `protobuf:"varint,17,opt,name=base_buy_price,json=baseBuyPrice,proto3" json:"base_buy_price,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WeaponDetail) Reset() {
	*x = WeaponDetail{}
	mi := &file_api_proto_items_items_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeaponDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeaponDetail) ProtoMessage() {}

func (x *WeaponDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_items_items_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeaponDetail.ProtoReflect.Descriptor instead.
func (*WeaponDetail) Descriptor() ([]byte, []int) {
	return file_api_proto_items_items_proto_rawDescGZIP(), []int{1}
}

func (x *WeaponDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WeaponDetail) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *WeaponDetail) GetRarityId() string {
	if x != nil {
		return x.RarityId
	}
	return ""
}

func (x *WeaponDetail) GetAttackPower() int32 {
	if x != nil {
		return x.AttackPower
	}
	return 0
}

func (x *WeaponDetail) GetDurability() int32 {
	if x != nil {
		return x.Durability
	}
	return 0
}

func (x *WeaponDetail) GetCriticalRate() float32 {
	if x != nil {
		return x.CriticalRate
	}
	return 0
}

func (x *WeaponDetail) GetWeaponType() string {
	if x != nil {
		return x.WeaponType
	}
	return ""
}

func (x *WeaponDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WeaponDetail) GetItemTemplateId() string {
	if x != nil {
		return x.ItemTemplateId
	}
	return ""
}

func (x *WeaponDetail) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *WeaponDetail) GetItemCode() string {
	if x != nil {
		return x.ItemCode
	}
	return ""
}

func (x *WeaponDetail) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *WeaponDetail) GetIsTradeable() bool {
	if x != nil {
		return x.IsTradeable
	}
	return false
}

func (x *WeaponDetail) GetIsDroppable() bool {
	if x != nil {
		return x.IsDroppable
	}
	return false
}

func (x *WeaponDetail) GetRequiredLevel() int32 {
	if x != nil {
		return x.RequiredLevel
	}
	return 0
}

func (x *WeaponDetail) GetBaseSellPrice() int32 {
	if x != nil {
		return x.BaseSellPrice
	}
	return 0
}

func (x *WeaponDetail) GetBaseBuyPrice() int32 {
	if x != nil {
		return x.BaseBuyPrice
	}
	return 0
}

func (x *WeaponDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WeaponDetail) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateWeaponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeId        string                 `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	RarityId      string                 `protobuf:"bytes,2,opt,name=rarity_id,json=rarityId,proto3" json:"rarity_id,omitempty"`
	AttackPower   int32                  `protobuf:"varint,3,opt,name=attack_power,json=attackPower,proto3" json:"attack_power,omitempty"`
	Durability    int32                  `protobuf:"varint,4,opt,name=durability,proto3" json:"durability,omitempty"`
	CriticalRate  float32                `protobuf:"fixed32,5,opt,name=critical_rate,json=criticalRate,proto3" json:"critical_rate,omitempty"`
	WeaponType    string                 `protobuf:"bytes,6,opt,name=weapon_type,json=weaponType,proto3" json:"weapon_type,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWeaponRequest) Reset() {
	*x = CreateWeaponRequest{}
	mi := &file_api_proto_items_items_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWeaponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWeaponRequest) ProtoMessage() {}

func (x *CreateWeaponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_items_items_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWeaponRequest.ProtoReflect.Descriptor instead.
func (*CreateWeaponRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_items_items_proto_rawDescGZIP(), []int{2}
}

func (x *CreateWeaponRequest) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *CreateWeaponRequest) GetRarityId() string {
	if x != nil {
		return x.RarityId
	}
	return ""
}

func (x *CreateWeaponRequest) GetAttackPower() int32 {
	if x != nil {
		return x.AttackPower
	}
	return 0
}

func (x *CreateWeaponRequest) GetDurability() int32 {
	if x != nil {
		return x.Durability
	}
	return 0
}

func (x *CreateWeaponRequest) GetCriticalRate() float32 {
	if x != nil {
		return x.CriticalRate
	}
	return 0
}

func (x *CreateWeaponRequest) GetWeaponType() string {
	if x != nil {
		return x.WeaponType
	}
	return ""
}

func (x *CreateWeaponRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetWeaponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeaponRequest) Reset() {
	*x = GetWeaponRequest{}
	mi := &file_api_proto_items_items_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeaponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeaponRequest) ProtoMessage() {}

func (x *GetWeaponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_items_items_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeaponRequest.ProtoReflect.Descriptor instead.
func (*GetWeaponRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_items_items_proto_rawDescGZIP(), []int{3}
}

func (x *GetWeaponRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListWeaponsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weapons       []*WeaponDetail        `protobuf:"bytes,1,rep,name=weapons,proto3" json:"weapons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWeaponsResponse) Reset() {
	*x = ListWeaponsResponse{}
	mi := &file_api_proto_items_items_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWeaponsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWeaponsResponse) ProtoMessage() {}

func (x *ListWeaponsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_items_items_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWeaponsResponse.ProtoReflect.Descriptor instead.
func (*ListWeaponsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_items_items_proto_rawDescGZIP(), []int{4}
}

func (x *ListWeaponsResponse) GetWeapons() []*WeaponDetail {
	if x != nil {
		return x.Weapons
	}
	return nil
}

// ArmorDetail (armors + item_templates joined)
type ArmorDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Armor fields
	Id              string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeId          string `protobuf:"bytes,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	RarityId        string `protobuf:"bytes,3,opt,name=rarity_id,json=rarityId,proto3" json:"rarity_id,omitempty"`
	DefenseRating   int32  `protobuf:"varint,4,opt,name=defense_rating,json=defenseRating,proto3" json:"defense_rating,omitempty"`
	Durability      int32  `protobuf:"varint,5,opt,name=durability,proto3" json:"durability,omitempty"`
	MagicResistance int32  `protobuf:"varint,6,opt,name=magic_resistance,json=magicResistance,proto3" json:"magic_resistance,omitempty"`
	ArmorSlot       string `protobuf:"bytes,7,opt,name=armor_slot,json=armorSlot,proto3" json:"armor_slot,omitempty"`
	Description     string `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	// ItemTemplate fields
	ItemTemplateId string                 `protobuf:"bytes,9,opt,name=item_template_id,json=itemTemplateId,proto3" json:"item_template_id,omitempty"`
	ItemName       string                 `protobuf:"bytes,10,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	ItemCode       string                 `protobuf:"bytes,11,opt,name=item_code,json=itemCode,proto3" json:"item_code,omitempty"`
	IconUrl        string                 `protobuf:"bytes,12,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	IsTradeable    bool                   `protobuf:"varint,13,opt,name=is_tradeable,json=isTradeable,proto3" json:"is_tradeable,omitempty"`
	IsDroppable    bool                   `protobuf:"varint,14,opt,name=is_droppable,json=isDroppable,proto3" json:"is_droppable,omitempty"`
	RequiredLevel  int32                  `protobuf:"varint,15,opt,name=required_level,json=requiredLevel,proto3" json:"required_level,omitempty"`
	BaseSellPrice  int32                  `protobuf:"varint,16,opt,name=base_sell_price,json=baseSellPrice,proto3" json:"base_sell_price,omitempty"`
	BaseBuyPrice   int32                  `protobuf:"varint,17,opt,name=base_buy_price,json=baseBuyPrice,proto3" json:"base_buy_price,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ArmorDetail) Reset() {
	*x = ArmorDetail{}
	mi := &file_api_proto_items_items_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArmorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArmorDetail) ProtoMessage() {}

func (x *ArmorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_items_items_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArmorDetail.ProtoReflect.Descriptor instead.
func (*ArmorDetail) Descriptor() ([]byte, []int) {
	return file_api_proto_items_items_proto_rawDescGZIP(), []int{5}
}

func (x *ArmorDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArmorDetail) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *ArmorDetail) GetRarityId() string {
	if x != nil {
		return x.RarityId
	}
	return ""
}

func (x *ArmorDetail) GetDefenseRating() int32 {
	if x != nil {
		return x.DefenseRating
	}
	return 0
}

func (x *ArmorDetail) GetDurability() int32 {
	if x != nil {
		return x.Durability
	}
	return 0
}

func (x *ArmorDetail) GetMagicResistance() int32 {
	if x != nil {
		return x.MagicResistance
	}
	return 0
}

func (x *ArmorDetail) GetArmorSlot() string {
	if x != nil {
		return x.ArmorSlot
	}
	return ""
}

func (x *ArmorDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ArmorDetail) GetItemTemplateId() string {
	if x != nil {
		return x.ItemTemplateId
	}
	return ""
}

func (x *ArmorDetail) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *ArmorDetail) GetItemCode() string {
	if x != nil {
		return x.ItemCode
	}
	return ""
}

func (x *ArmorDetail) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *ArmorDetail) GetIsTradeable() bool {
	if x != nil {
		return x.IsTradeable
	}
	return false
}

func (x *ArmorDetail) GetIsDroppable() bool {
	if x != nil {
		return x.IsDroppable
	}
	return false
}

func (x *ArmorDetail) GetRequiredLevel() int32 {
	if x != nil {
		return x.RequiredLevel
	}
	return 0
}

func (x *ArmorDetail) GetBaseSellPrice() int32 {
	if x != nil {
		return x.BaseSellPrice
	}
	return 0
}

func (x *ArmorDetail) GetBaseBuyPrice() int32 {
	if x != nil {
		return x.BaseBuyPrice
	}
	return 0
}

func (x *ArmorDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ArmorDetail) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListArmorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Armors        []*ArmorDetail         `protobuf:"bytes,1,rep,name=armors,proto3" json:"armors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArmorsResponse) Reset() {
	*x = ListArmorsResponse{}
	mi := &file_api_proto_items_items_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArmorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArmorsResponse) ProtoMessage() {}

func (x *ListArmorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_items_items_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArmorsResponse.ProtoReflect.Descriptor instead.
func (*ListArmorsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_items_items_proto_rawDescGZIP(), []int{6}
}

func (x *ListArmorsResponse) GetArmors() []*ArmorDetail {
	if x != nil {
		return x.Armors
	}
	return nil
}

// ConsumableDetail (consumables + item_templates joined)
type ConsumableDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Consumable fields
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeId        string `protobuf:"bytes,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	RarityId      string `protobuf:"bytes,3,opt,name=rarity_id,json=rarityId,proto3" json:"rarity_id,omitempty"`
	HealingAmount int32  `protobuf:"varint,4,opt,name=healing_amount,json=healingAmount,proto3" json:"healing_amount,omitempty"`
	ManaAmount    int32  `protobuf:"varint,5,opt,name=mana_amount,json=manaAmount,proto3" json:"mana_amount,omitempty"`
	BuffDuration  int32  `protobuf:"varint,6,opt,name=buff_duration,json=buffDuration,proto3" json:"buff_duration,omitempty"`
	MaxStackSize  int32  `protobuf:"varint,7,opt,name=max_stack_size,json=maxStackSize,proto3" json:"max_stack_size,omitempty"`
	Description   string `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	// ItemTemplate fields
	ItemTemplateId string                 `protobuf:"bytes,9,opt,name=item_template_id,json=itemTemplateId,proto3" json:"item_template_id,omitempty"`
	ItemName       string                 `protobuf:"bytes,10,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	ItemCode       string                 `protobuf:"bytes,11,opt,name=item_code,json=itemCode,proto3" json:"item_code,omitempty"`
	IconUrl        string                 `protobuf:"bytes,12,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	IsTradeable    bool                   `protobuf:"varint,13,opt,name=is_tradeable,json=isTradeable,proto3" json:"is_tradeable,omitempty"`
	IsDroppable    bool                   `protobuf:"varint,14,opt,name=is_droppable,json=isDroppable,proto3" json:"is_droppable,omitempty"`
	RequiredLevel  int32                  `protobuf:"varint,15,opt,name=required_level,json=requiredLevel,proto3" json:"required_level,omitempty"`
	BaseSellPrice  int32                  `protobuf:"varint,16,opt,name=base_sell_price,json=baseSellPrice,proto3" json:"base_sell_price,omitempty"`
	BaseBuyPrice   int32                  `protobuf:"varint,17,opt,name=base_buy_price,json=baseBuyPrice,proto3" json:"base_buy_price,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConsumableDetail) Reset() {
	*x = ConsumableDetail{}
	mi := &file_api_proto_items_items_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumableDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumableDetail) ProtoMessage() {}

func (x *ConsumableDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_items_items_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumableDetail.ProtoReflect.Descriptor instead.
func (*ConsumableDetail) Descriptor() ([]byte, []int) {
	return file_api_proto_items_items_proto_rawDescGZIP(), []int{7}
}

func (x *ConsumableDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConsumableDetail) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *ConsumableDetail) GetRarityId() string {
	if x != nil {
		return x.RarityId
	}
	return ""
}

func (x *ConsumableDetail) GetHealingAmount() int32 {
	if x != nil {
		return x.HealingAmount
	}
	return 0
}

func (x *ConsumableDetail) GetManaAmount() int32 {
	if x != nil {
		return x.ManaAmount
	}
	return 0
}

func (x *ConsumableDetail) GetBuffDuration() int32 {
	if x != nil {
		return x.BuffDuration
	}
	return 0
}

func (x *ConsumableDetail) GetMaxStackSize() int32 {
	if x != nil {
		return x.MaxStackSize
	}
	return 0
}

func (x *ConsumableDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConsumableDetail) GetItemTemplateId() string {
	if x != nil {
		return x.ItemTemplateId
	}
	return ""
}

func (x *ConsumableDetail) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *ConsumableDetail) GetItemCode() string {
	if x != nil {
		return x.ItemCode
	}
	return ""
}

func (x *ConsumableDetail) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *ConsumableDetail) GetIsTradeable() bool {
	if x != nil {
		return x.IsTradeable
	}
	return false
}

func (x *ConsumableDetail) GetIsDroppable() bool {
	if x != nil {
		return x.IsDroppable
	}
	return false
}

func (x *ConsumableDetail) GetRequiredLevel() int32 {
	if x != nil {
		return x.RequiredLevel
	}
	return 0
}

func (x *ConsumableDetail) GetBaseSellPrice() int32 {
	if x != nil {
		return x.BaseSellPrice
	}
	return 0
}

func (x *ConsumableDetail) GetBaseBuyPrice() int32 {
	if x != nil {
		return x.BaseBuyPrice
	}
	return 0
}

func (x *ConsumableDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ConsumableDetail) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListConsumablesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consumables   []*ConsumableDetail    `protobuf:"bytes,1,rep,name=consumables,proto3" json:"consumables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsumablesResponse) Reset() {
	*x = ListConsumablesResponse{}
	mi := &file_api_proto_items_items_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsumablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsumablesResponse) ProtoMessage() {}

func (x *ListConsumablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_items_items_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsumablesResponse.ProtoReflect.Descriptor instead.
func (*ListConsumablesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_items_items_proto_rawDescGZIP(), []int{8}
}

func (x *ListConsumablesResponse) GetConsumables() []*ConsumableDetail {
	if x != nil {
		return x.Consumables
	}
	return nil
}

// ItemTemplate (unified item template)
type ItemTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	ItemCode      string                 `protobuf:"bytes,3,opt,name=item_code,json=itemCode,proto3" json:"item_code,omitempty"`
	TypeId        string                 `protobuf:"bytes,4,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	RarityId      string                 `protobuf:"bytes,5,opt,name=rarity_id,json=rarityId,proto3" json:"rarity_id,omitempty"`
	ItemType      string                 `protobuf:"bytes,6,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"` // 'weapon', 'armor', 'consumable'
	ItemId        string                 `protobuf:"bytes,7,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`       // references weapon/armor/consumable id
	IconUrl       string                 `protobuf:"bytes,8,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	IsTradeable   bool                   `protobuf:"varint,9,opt,name=is_tradeable,json=isTradeable,proto3" json:"is_tradeable,omitempty"`
	IsDroppable   bool                   `protobuf:"varint,10,opt,name=is_droppable,json=isDroppable,proto3" json:"is_droppable,omitempty"`
	RequiredLevel int32                  `protobuf:"varint,11,opt,name=required_level,json=requiredLevel,proto3" json:"required_level,omitempty"`
	BaseSellPrice int32                  `protobuf:"varint,12,opt,name=base_sell_price,json=baseSellPrice,proto3" json:"base_sell_price,omitempty"`
	BaseBuyPrice  int32                  `protobuf:"varint,13,opt,name=base_buy_price,json=baseBuyPrice,proto3" json:"base_buy_price,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemTemplate) Reset() {
	*x = ItemTemplate{}
	mi := &file_api_proto_items_items_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemTemplate) ProtoMessage() {}

func (x *ItemTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_items_items_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemTemplate.ProtoReflect.Descriptor instead.
func (*ItemTemplate) Descriptor() ([]byte, []int) {
	return file_api_proto_items_items_proto_rawDescGZIP(), []int{9}
}

func (x *ItemTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemTemplate) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *ItemTemplate) GetItemCode() string {
	if x != nil {
		return x.ItemCode
	}
	return ""
}

func (x *ItemTemplate) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *ItemTemplate) GetRarityId() string {
	if x != nil {
		return x.RarityId
	}
	return ""
}

func (x *ItemTemplate) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *ItemTemplate) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ItemTemplate) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *ItemTemplate) GetIsTradeable() bool {
	if x != nil {
		return x.IsTradeable
	}
	return false
}

func (x *ItemTemplate) GetIsDroppable() bool {
	if x != nil {
		return x.IsDroppable
	}
	return false
}

func (x *ItemTemplate) GetRequiredLevel() int32 {
	if x != nil {
		return x.RequiredLevel
	}
	return 0
}

func (x *ItemTemplate) GetBaseSellPrice() int32 {
	if x != nil {
		return x.BaseSellPrice
	}
	return 0
}

func (x *ItemTemplate) GetBaseBuyPrice() int32 {
	if x != nil {
		return x.BaseBuyPrice
	}
	return 0
}

func (x *ItemTemplate) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ItemTemplate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateItemTemplateRequest for creating item templates
// Note: user_id will be extracted from JWT token in API Gateway
type CreateItemTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Admin user ID (from JWT)
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	ItemCode      string                 `protobuf:"bytes,3,opt,name=item_code,json=itemCode,proto3" json:"item_code,omitempty"`
	TypeId        string                 `protobuf:"bytes,4,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	RarityId      string                 `protobuf:"bytes,5,opt,name=rarity_id,json=rarityId,proto3" json:"rarity_id,omitempty"`
	ItemType      string                 `protobuf:"bytes,6,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"` // 'weapon', 'armor', 'consumable'
	ItemId        string                 `protobuf:"bytes,7,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`       // references weapon/armor/consumable id
	IconUrl       *string                `protobuf:"bytes,8,opt,name=icon_url,json=iconUrl,proto3,oneof" json:"icon_url,omitempty"`
	IsTradeable   *bool                  `protobuf:"varint,9,opt,name=is_tradeable,json=isTradeable,proto3,oneof" json:"is_tradeable,omitempty"`
	IsDroppable   *bool                  `protobuf:"varint,10,opt,name=is_droppable,json=isDroppable,proto3,oneof" json:"is_droppable,omitempty"`
	RequiredLevel *int32                 `protobuf:"varint,11,opt,name=required_level,json=requiredLevel,proto3,oneof" json:"required_level,omitempty"`
	BaseSellPrice *int32                 `protobuf:"varint,12,opt,name=base_sell_price,json=baseSellPrice,proto3,oneof" json:"base_sell_price,omitempty"`
	BaseBuyPrice  *int32                 `protobuf:"varint,13,opt,name=base_buy_price,json=baseBuyPrice,proto3,oneof" json:"base_buy_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemTemplateRequest) Reset() {
	*x = CreateItemTemplateRequest{}
	mi := &file_api_proto_items_items_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemTemplateRequest) ProtoMessage() {}

func (x *CreateItemTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_items_items_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateItemTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_items_items_proto_rawDescGZIP(), []int{10}
}

func (x *CreateItemTemplateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateItemTemplateRequest) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *CreateItemTemplateRequest) GetItemCode() string {
	if x != nil {
		return x.ItemCode
	}
	return ""
}

func (x *CreateItemTemplateRequest) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *CreateItemTemplateRequest) GetRarityId() string {
	if x != nil {
		return x.RarityId
	}
	return ""
}

func (x *CreateItemTemplateRequest) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *CreateItemTemplateRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *CreateItemTemplateRequest) GetIconUrl() string {
	if x != nil && x.IconUrl != nil {
		return *x.IconUrl
	}
	return ""
}

func (x *CreateItemTemplateRequest) GetIsTradeable() bool {
	if x != nil && x.IsTradeable != nil {
		return *x.IsTradeable
	}
	return false
}

func (x *CreateItemTemplateRequest) GetIsDroppable() bool {
	if x != nil && x.IsDroppable != nil {
		return *x.IsDroppable
	}
	return false
}

func (x *CreateItemTemplateRequest) GetRequiredLevel() int32 {
	if x != nil && x.RequiredLevel != nil {
		return *x.RequiredLevel
	}
	return 0
}

func (x *CreateItemTemplateRequest) GetBaseSellPrice() int32 {
	if x != nil && x.BaseSellPrice != nil {
		return *x.BaseSellPrice
	}
	return 0
}

func (x *CreateItemTemplateRequest) GetBaseBuyPrice() int32 {
	if x != nil && x.BaseBuyPrice != nil {
		return *x.BaseBuyPrice
	}
	return 0
}

var File_api_proto_items_items_proto protoreflect.FileDescriptor

const file_api_proto_items_items_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/items/items.proto\x12\x05items\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xef\x02\n" +
	"\x06Weapon\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atype_id\x18\x02 \x01(\tR\x06typeId\x12\x1b\n" +
	"\trarity_id\x18\x03 \x01(\tR\brarityId\x12!\n" +
	"\fattack_power\x18\x04 \x01(\x05R\vattackPower\x12\x1e\n" +
	"\n" +
	"durability\x18\x05 \x01(\x05R\n" +
	"durability\x12#\n" +
	"\rcritical_rate\x18\x06 \x01(\x02R\fcriticalRate\x12\x1f\n" +
	"\vweapon_type\x18\a \x01(\tR\n" +
	"weaponType\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xaf\x05\n" +
	"\fWeaponDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atype_id\x18\x02 \x01(\tR\x06typeId\x12\x1b\n" +
	"\trarity_id\x18\x03 \x01(\tR\brarityId\x12!\n" +
	"\fattack_power\x18\x04 \x01(\x05R\vattackPower\x12\x1e\n" +
	"\n" +
	"durability\x18\x05 \x01(\x05R\n" +
	"durability\x12#\n" +
	"\rcritical_rate\x18\x06 \x01(\x02R\fcriticalRate\x12\x1f\n" +
	"\vweapon_type\x18\a \x01(\tR\n" +
	"weaponType\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12(\n" +
	"\x10item_template_id\x18\t \x01(\tR\x0eitemTemplateId\x12\x1b\n" +
	"\titem_name\x18\n" +
	" \x01(\tR\bitemName\x12\x1b\n" +
	"\titem_code\x18\v \x01(\tR\bitemCode\x12\x19\n" +
	"\bicon_url\x18\f \x01(\tR\aiconUrl\x12!\n" +
	"\fis_tradeable\x18\r \x01(\bR\visTradeable\x12!\n" +
	"\fis_droppable\x18\x0e \x01(\bR\visDroppable\x12%\n" +
	"\x0erequired_level\x18\x0f \x01(\x05R\rrequiredLevel\x12&\n" +
	"\x0fbase_sell_price\x18\x10 \x01(\x05R\rbaseSellPrice\x12$\n" +
	"\x0ebase_buy_price\x18\x11 \x01(\x05R\fbaseBuyPrice\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf6\x01\n" +
	"\x13CreateWeaponRequest\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\tR\x06typeId\x12\x1b\n" +
	"\trarity_id\x18\x02 \x01(\tR\brarityId\x12!\n" +
	"\fattack_power\x18\x03 \x01(\x05R\vattackPower\x12\x1e\n" +
	"\n" +
	"durability\x18\x04 \x01(\x05R\n" +
	"durability\x12#\n" +
	"\rcritical_rate\x18\x05 \x01(\x02R\fcriticalRate\x12\x1f\n" +
	"\vweapon_type\x18\x06 \x01(\tR\n" +
	"weaponType\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"\"\n" +
	"\x10GetWeaponRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x13ListWeaponsResponse\x12-\n" +
	"\aweapons\x18\x01 \x03(\v2\x13.items.WeaponDetailR\aweapons\"\xb6\x05\n" +
	"\vArmorDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atype_id\x18\x02 \x01(\tR\x06typeId\x12\x1b\n" +
	"\trarity_id\x18\x03 \x01(\tR\brarityId\x12%\n" +
	"\x0edefense_rating\x18\x04 \x01(\x05R\rdefenseRating\x12\x1e\n" +
	"\n" +
	"durability\x18\x05 \x01(\x05R\n" +
	"durability\x12)\n" +
	"\x10magic_resistance\x18\x06 \x01(\x05R\x0fmagicResistance\x12\x1d\n" +
	"\n" +
	"armor_slot\x18\a \x01(\tR\tarmorSlot\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12(\n" +
	"\x10item_template_id\x18\t \x01(\tR\x0eitemTemplateId\x12\x1b\n" +
	"\titem_name\x18\n" +
	" \x01(\tR\bitemName\x12\x1b\n" +
	"\titem_code\x18\v \x01(\tR\bitemCode\x12\x19\n" +
	"\bicon_url\x18\f \x01(\tR\aiconUrl\x12!\n" +
	"\fis_tradeable\x18\r \x01(\bR\visTradeable\x12!\n" +
	"\fis_droppable\x18\x0e \x01(\bR\visDroppable\x12%\n" +
	"\x0erequired_level\x18\x0f \x01(\x05R\rrequiredLevel\x12&\n" +
	"\x0fbase_sell_price\x18\x10 \x01(\x05R\rbaseSellPrice\x12$\n" +
	"\x0ebase_buy_price\x18\x11 \x01(\x05R\fbaseBuyPrice\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"@\n" +
	"\x12ListArmorsResponse\x12*\n" +
	"\x06armors\x18\x01 \x03(\v2\x12.items.ArmorDetailR\x06armors\"\xbd\x05\n" +
	"\x10ConsumableDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atype_id\x18\x02 \x01(\tR\x06typeId\x12\x1b\n" +
	"\trarity_id\x18\x03 \x01(\tR\brarityId\x12%\n" +
	"\x0ehealing_amount\x18\x04 \x01(\x05R\rhealingAmount\x12\x1f\n" +
	"\vmana_amount\x18\x05 \x01(\x05R\n" +
	"manaAmount\x12#\n" +
	"\rbuff_duration\x18\x06 \x01(\x05R\fbuffDuration\x12$\n" +
	"\x0emax_stack_size\x18\a \x01(\x05R\fmaxStackSize\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12(\n" +
	"\x10item_template_id\x18\t \x01(\tR\x0eitemTemplateId\x12\x1b\n" +
	"\titem_name\x18\n" +
	" \x01(\tR\bitemName\x12\x1b\n" +
	"\titem_code\x18\v \x01(\tR\bitemCode\x12\x19\n" +
	"\bicon_url\x18\f \x01(\tR\aiconUrl\x12!\n" +
	"\fis_tradeable\x18\r \x01(\bR\visTradeable\x12!\n" +
	"\fis_droppable\x18\x0e \x01(\bR\visDroppable\x12%\n" +
	"\x0erequired_level\x18\x0f \x01(\x05R\rrequiredLevel\x12&\n" +
	"\x0fbase_sell_price\x18\x10 \x01(\x05R\rbaseSellPrice\x12$\n" +
	"\x0ebase_buy_price\x18\x11 \x01(\x05R\fbaseBuyPrice\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"T\n" +
	"\x17ListConsumablesResponse\x129\n" +
	"\vconsumables\x18\x01 \x03(\v2\x17.items.ConsumableDetailR\vconsumables\"\x90\x04\n" +
	"\fItemTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12\x1b\n" +
	"\titem_code\x18\x03 \x01(\tR\bitemCode\x12\x17\n" +
	"\atype_id\x18\x04 \x01(\tR\x06typeId\x12\x1b\n" +
	"\trarity_id\x18\x05 \x01(\tR\brarityId\x12\x1b\n" +
	"\titem_type\x18\x06 \x01(\tR\bitemType\x12\x17\n" +
	"\aitem_id\x18\a \x01(\tR\x06itemId\x12\x19\n" +
	"\bicon_url\x18\b \x01(\tR\aiconUrl\x12!\n" +
	"\fis_tradeable\x18\t \x01(\bR\visTradeable\x12!\n" +
	"\fis_droppable\x18\n" +
	" \x01(\bR\visDroppable\x12%\n" +
	"\x0erequired_level\x18\v \x01(\x05R\rrequiredLevel\x12&\n" +
	"\x0fbase_sell_price\x18\f \x01(\x05R\rbaseSellPrice\x12$\n" +
	"\x0ebase_buy_price\x18\r \x01(\x05R\fbaseBuyPrice\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb7\x04\n" +
	"\x19CreateItemTemplateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12\x1b\n" +
	"\titem_code\x18\x03 \x01(\tR\bitemCode\x12\x17\n" +
	"\atype_id\x18\x04 \x01(\tR\x06typeId\x12\x1b\n" +
	"\trarity_id\x18\x05 \x01(\tR\brarityId\x12\x1b\n" +
	"\titem_type\x18\x06 \x01(\tR\bitemType\x12\x17\n" +
	"\aitem_id\x18\a \x01(\tR\x06itemId\x12\x1e\n" +
	"\bicon_url\x18\b \x01(\tH\x00R\aiconUrl\x88\x01\x01\x12&\n" +
	"\fis_tradeable\x18\t \x01(\bH\x01R\visTradeable\x88\x01\x01\x12&\n" +
	"\fis_droppable\x18\n" +
	" \x01(\bH\x02R\visDroppable\x88\x01\x01\x12*\n" +
	"\x0erequired_level\x18\v \x01(\x05H\x03R\rrequiredLevel\x88\x01\x01\x12+\n" +
	"\x0fbase_sell_price\x18\f \x01(\x05H\x04R\rbaseSellPrice\x88\x01\x01\x12)\n" +
	"\x0ebase_buy_price\x18\r \x01(\x05H\x05R\fbaseBuyPrice\x88\x01\x01B\v\n" +
	"\t_icon_urlB\x0f\n" +
	"\r_is_tradeableB\x0f\n" +
	"\r_is_droppableB\x11\n" +
	"\x0f_required_levelB\x12\n" +
	"\x10_base_sell_priceB\x11\n" +
	"\x0f_base_buy_price2\xd4\x03\n" +
	"\fItemsService\x129\n" +
	"\fCreateWeapon\x12\x1a.items.CreateWeaponRequest\x1a\r.items.Weapon\x12I\n" +
	"\x19GetWeaponWithTemplateByID\x12\x17.items.GetWeaponRequest\x1a\x13.items.WeaponDetail\x12M\n" +
	"\x17ListWeaponsWithTemplate\x12\x16.google.protobuf.Empty\x1a\x1a.items.ListWeaponsResponse\x12K\n" +
	"\x16ListArmorsWithTemplate\x12\x16.google.protobuf.Empty\x1a\x19.items.ListArmorsResponse\x12U\n" +
	"\x1bListConsumablesWithTemplate\x12\x16.google.protobuf.Empty\x1a\x1e.items.ListConsumablesResponse\x12K\n" +
	"\x12CreateItemTemplate\x12 .items.CreateItemTemplateRequest\x1a\x13.items.ItemTemplateBCZAgithub.com/darkphotonKN/cosmic-void-server/common/api/proto/itemsb\x06proto3"

var (
	file_api_proto_items_items_proto_rawDescOnce sync.Once
	file_api_proto_items_items_proto_rawDescData []byte
)

func file_api_proto_items_items_proto_rawDescGZIP() []byte {
	file_api_proto_items_items_proto_rawDescOnce.Do(func() {
		file_api_proto_items_items_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_items_items_proto_rawDesc), len(file_api_proto_items_items_proto_rawDesc)))
	})
	return file_api_proto_items_items_proto_rawDescData
}

var file_api_proto_items_items_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_items_items_proto_goTypes = []any{
	(*Weapon)(nil),                    // 0: items.Weapon
	(*WeaponDetail)(nil),              // 1: items.WeaponDetail
	(*CreateWeaponRequest)(nil),       // 2: items.CreateWeaponRequest
	(*GetWeaponRequest)(nil),          // 3: items.GetWeaponRequest
	(*ListWeaponsResponse)(nil),       // 4: items.ListWeaponsResponse
	(*ArmorDetail)(nil),               // 5: items.ArmorDetail
	(*ListArmorsResponse)(nil),        // 6: items.ListArmorsResponse
	(*ConsumableDetail)(nil),          // 7: items.ConsumableDetail
	(*ListConsumablesResponse)(nil),   // 8: items.ListConsumablesResponse
	(*ItemTemplate)(nil),              // 9: items.ItemTemplate
	(*CreateItemTemplateRequest)(nil), // 10: items.CreateItemTemplateRequest
	(*timestamppb.Timestamp)(nil),     // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 12: google.protobuf.Empty
}
var file_api_proto_items_items_proto_depIdxs = []int32{
	11, // 0: items.Weapon.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: items.Weapon.updated_at:type_name -> google.protobuf.Timestamp
	11, // 2: items.WeaponDetail.created_at:type_name -> google.protobuf.Timestamp
	11, // 3: items.WeaponDetail.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: items.ListWeaponsResponse.weapons:type_name -> items.WeaponDetail
	11, // 5: items.ArmorDetail.created_at:type_name -> google.protobuf.Timestamp
	11, // 6: items.ArmorDetail.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 7: items.ListArmorsResponse.armors:type_name -> items.ArmorDetail
	11, // 8: items.ConsumableDetail.created_at:type_name -> google.protobuf.Timestamp
	11, // 9: items.ConsumableDetail.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 10: items.ListConsumablesResponse.consumables:type_name -> items.ConsumableDetail
	11, // 11: items.ItemTemplate.created_at:type_name -> google.protobuf.Timestamp
	11, // 12: items.ItemTemplate.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 13: items.ItemsService.CreateWeapon:input_type -> items.CreateWeaponRequest
	3,  // 14: items.ItemsService.GetWeaponWithTemplateByID:input_type -> items.GetWeaponRequest
	12, // 15: items.ItemsService.ListWeaponsWithTemplate:input_type -> google.protobuf.Empty
	12, // 16: items.ItemsService.ListArmorsWithTemplate:input_type -> google.protobuf.Empty
	12, // 17: items.ItemsService.ListConsumablesWithTemplate:input_type -> google.protobuf.Empty
	10, // 18: items.ItemsService.CreateItemTemplate:input_type -> items.CreateItemTemplateRequest
	0,  // 19: items.ItemsService.CreateWeapon:output_type -> items.Weapon
	1,  // 20: items.ItemsService.GetWeaponWithTemplateByID:output_type -> items.WeaponDetail
	4,  // 21: items.ItemsService.ListWeaponsWithTemplate:output_type -> items.ListWeaponsResponse
	6,  // 22: items.ItemsService.ListArmorsWithTemplate:output_type -> items.ListArmorsResponse
	8,  // 23: items.ItemsService.ListConsumablesWithTemplate:output_type -> items.ListConsumablesResponse
	9,  // 24: items.ItemsService.CreateItemTemplate:output_type -> items.ItemTemplate
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_proto_items_items_proto_init() }
func file_api_proto_items_items_proto_init() {
	if File_api_proto_items_items_proto != nil {
		return
	}
	file_api_proto_items_items_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_items_items_proto_rawDesc), len(file_api_proto_items_items_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_items_items_proto_goTypes,
		DependencyIndexes: file_api_proto_items_items_proto_depIdxs,
		MessageInfos:      file_api_proto_items_items_proto_msgTypes,
	}.Build()
	File_api_proto_items_items_proto = out.File
	file_api_proto_items_items_proto_goTypes = nil
	file_api_proto_items_items_proto_depIdxs = nil
}
