// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: api/proto/items/items.proto

package items

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ItemsService_CreateWeapon_FullMethodName                = "/items.ItemsService/CreateWeapon"
	ItemsService_GetWeaponWithTemplateByID_FullMethodName   = "/items.ItemsService/GetWeaponWithTemplateByID"
	ItemsService_ListWeaponsWithTemplate_FullMethodName     = "/items.ItemsService/ListWeaponsWithTemplate"
	ItemsService_ListArmorsWithTemplate_FullMethodName      = "/items.ItemsService/ListArmorsWithTemplate"
	ItemsService_ListConsumablesWithTemplate_FullMethodName = "/items.ItemsService/ListConsumablesWithTemplate"
)

// ItemsServiceClient is the client API for ItemsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ItemsService external API for items
type ItemsServiceClient interface {
	// Weapon operations
	CreateWeapon(ctx context.Context, in *CreateWeaponRequest, opts ...grpc.CallOption) (*Weapon, error)
	GetWeaponWithTemplateByID(ctx context.Context, in *GetWeaponRequest, opts ...grpc.CallOption) (*WeaponDetail, error)
	ListWeaponsWithTemplate(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListWeaponsResponse, error)
	// Armor operations
	ListArmorsWithTemplate(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListArmorsResponse, error)
	// Consumable operations
	ListConsumablesWithTemplate(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListConsumablesResponse, error)
}

type itemsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewItemsServiceClient(cc grpc.ClientConnInterface) ItemsServiceClient {
	return &itemsServiceClient{cc}
}

func (c *itemsServiceClient) CreateWeapon(ctx context.Context, in *CreateWeaponRequest, opts ...grpc.CallOption) (*Weapon, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Weapon)
	err := c.cc.Invoke(ctx, ItemsService_CreateWeapon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemsServiceClient) GetWeaponWithTemplateByID(ctx context.Context, in *GetWeaponRequest, opts ...grpc.CallOption) (*WeaponDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WeaponDetail)
	err := c.cc.Invoke(ctx, ItemsService_GetWeaponWithTemplateByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemsServiceClient) ListWeaponsWithTemplate(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListWeaponsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWeaponsResponse)
	err := c.cc.Invoke(ctx, ItemsService_ListWeaponsWithTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemsServiceClient) ListArmorsWithTemplate(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListArmorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArmorsResponse)
	err := c.cc.Invoke(ctx, ItemsService_ListArmorsWithTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemsServiceClient) ListConsumablesWithTemplate(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListConsumablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConsumablesResponse)
	err := c.cc.Invoke(ctx, ItemsService_ListConsumablesWithTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemsServiceServer is the server API for ItemsService service.
// All implementations must embed UnimplementedItemsServiceServer
// for forward compatibility.
//
// ItemsService external API for items
type ItemsServiceServer interface {
	// Weapon operations
	CreateWeapon(context.Context, *CreateWeaponRequest) (*Weapon, error)
	GetWeaponWithTemplateByID(context.Context, *GetWeaponRequest) (*WeaponDetail, error)
	ListWeaponsWithTemplate(context.Context, *emptypb.Empty) (*ListWeaponsResponse, error)
	// Armor operations
	ListArmorsWithTemplate(context.Context, *emptypb.Empty) (*ListArmorsResponse, error)
	// Consumable operations
	ListConsumablesWithTemplate(context.Context, *emptypb.Empty) (*ListConsumablesResponse, error)
	mustEmbedUnimplementedItemsServiceServer()
}

// UnimplementedItemsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedItemsServiceServer struct{}

func (UnimplementedItemsServiceServer) CreateWeapon(context.Context, *CreateWeaponRequest) (*Weapon, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWeapon not implemented")
}
func (UnimplementedItemsServiceServer) GetWeaponWithTemplateByID(context.Context, *GetWeaponRequest) (*WeaponDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWeaponWithTemplateByID not implemented")
}
func (UnimplementedItemsServiceServer) ListWeaponsWithTemplate(context.Context, *emptypb.Empty) (*ListWeaponsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWeaponsWithTemplate not implemented")
}
func (UnimplementedItemsServiceServer) ListArmorsWithTemplate(context.Context, *emptypb.Empty) (*ListArmorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListArmorsWithTemplate not implemented")
}
func (UnimplementedItemsServiceServer) ListConsumablesWithTemplate(context.Context, *emptypb.Empty) (*ListConsumablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConsumablesWithTemplate not implemented")
}
func (UnimplementedItemsServiceServer) mustEmbedUnimplementedItemsServiceServer() {}
func (UnimplementedItemsServiceServer) testEmbeddedByValue()                      {}

// UnsafeItemsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ItemsServiceServer will
// result in compilation errors.
type UnsafeItemsServiceServer interface {
	mustEmbedUnimplementedItemsServiceServer()
}

func RegisterItemsServiceServer(s grpc.ServiceRegistrar, srv ItemsServiceServer) {
	// If the following call pancis, it indicates UnimplementedItemsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ItemsService_ServiceDesc, srv)
}

func _ItemsService_CreateWeapon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWeaponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServiceServer).CreateWeapon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemsService_CreateWeapon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServiceServer).CreateWeapon(ctx, req.(*CreateWeaponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemsService_GetWeaponWithTemplateByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeaponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServiceServer).GetWeaponWithTemplateByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemsService_GetWeaponWithTemplateByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServiceServer).GetWeaponWithTemplateByID(ctx, req.(*GetWeaponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemsService_ListWeaponsWithTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServiceServer).ListWeaponsWithTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemsService_ListWeaponsWithTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServiceServer).ListWeaponsWithTemplate(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemsService_ListArmorsWithTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServiceServer).ListArmorsWithTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemsService_ListArmorsWithTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServiceServer).ListArmorsWithTemplate(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemsService_ListConsumablesWithTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServiceServer).ListConsumablesWithTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ItemsService_ListConsumablesWithTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServiceServer).ListConsumablesWithTemplate(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ItemsService_ServiceDesc is the grpc.ServiceDesc for ItemsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ItemsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "items.ItemsService",
	HandlerType: (*ItemsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWeapon",
			Handler:    _ItemsService_CreateWeapon_Handler,
		},
		{
			MethodName: "GetWeaponWithTemplateByID",
			Handler:    _ItemsService_GetWeaponWithTemplateByID_Handler,
		},
		{
			MethodName: "ListWeaponsWithTemplate",
			Handler:    _ItemsService_ListWeaponsWithTemplate_Handler,
		},
		{
			MethodName: "ListArmorsWithTemplate",
			Handler:    _ItemsService_ListArmorsWithTemplate_Handler,
		},
		{
			MethodName: "ListConsumablesWithTemplate",
			Handler:    _ItemsService_ListConsumablesWithTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/items/items.proto",
}
