// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/proto/items/items.proto

package items

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Layer 1: Basic Weapon (weapons table only - for create/simple queries)
type Weapon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeId        string                 `protobuf:"bytes,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	RarityId      string                 `protobuf:"bytes,3,opt,name=rarity_id,json=rarityId,proto3" json:"rarity_id,omitempty"`
	AttackPower   int32                  `protobuf:"varint,4,opt,name=attack_power,json=attackPower,proto3" json:"attack_power,omitempty"`
	Durability    int32                  `protobuf:"varint,5,opt,name=durability,proto3" json:"durability,omitempty"`
	CriticalRate  float32                `protobuf:"fixed32,6,opt,name=critical_rate,json=criticalRate,proto3" json:"critical_rate,omitempty"`
	WeaponType    string                 `protobuf:"bytes,7,opt,name=weapon_type,json=weaponType,proto3" json:"weapon_type,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weapon) Reset() {
	*x = Weapon{}
	mi := &file_api_proto_items_items_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weapon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weapon) ProtoMessage() {}

func (x *Weapon) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_items_items_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weapon.ProtoReflect.Descriptor instead.
func (*Weapon) Descriptor() ([]byte, []int) {
	return file_api_proto_items_items_proto_rawDescGZIP(), []int{0}
}

func (x *Weapon) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Weapon) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *Weapon) GetRarityId() string {
	if x != nil {
		return x.RarityId
	}
	return ""
}

func (x *Weapon) GetAttackPower() int32 {
	if x != nil {
		return x.AttackPower
	}
	return 0
}

func (x *Weapon) GetDurability() int32 {
	if x != nil {
		return x.Durability
	}
	return 0
}

func (x *Weapon) GetCriticalRate() float32 {
	if x != nil {
		return x.CriticalRate
	}
	return 0
}

func (x *Weapon) GetWeaponType() string {
	if x != nil {
		return x.WeaponType
	}
	return ""
}

func (x *Weapon) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Weapon) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Weapon) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Layer 2: WeaponDetail (weapons + item_templates joined - for detailed queries)
type WeaponDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Weapon specific fields (from weapons table)
	Id           string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeId       string  `protobuf:"bytes,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	RarityId     string  `protobuf:"bytes,3,opt,name=rarity_id,json=rarityId,proto3" json:"rarity_id,omitempty"`
	AttackPower  int32   `protobuf:"varint,4,opt,name=attack_power,json=attackPower,proto3" json:"attack_power,omitempty"`
	Durability   int32   `protobuf:"varint,5,opt,name=durability,proto3" json:"durability,omitempty"`
	CriticalRate float32 `protobuf:"fixed32,6,opt,name=critical_rate,json=criticalRate,proto3" json:"critical_rate,omitempty"`
	WeaponType   string  `protobuf:"bytes,7,opt,name=weapon_type,json=weaponType,proto3" json:"weapon_type,omitempty"`
	Description  string  `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	// ItemTemplate fields (from item_templates table)
	ItemTemplateId string                 `protobuf:"bytes,9,opt,name=item_template_id,json=itemTemplateId,proto3" json:"item_template_id,omitempty"`
	ItemName       string                 `protobuf:"bytes,10,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	ItemCode       string                 `protobuf:"bytes,11,opt,name=item_code,json=itemCode,proto3" json:"item_code,omitempty"`
	IconUrl        string                 `protobuf:"bytes,12,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	IsTradeable    bool                   `protobuf:"varint,13,opt,name=is_tradeable,json=isTradeable,proto3" json:"is_tradeable,omitempty"`
	IsDroppable    bool                   `protobuf:"varint,14,opt,name=is_droppable,json=isDroppable,proto3" json:"is_droppable,omitempty"`
	RequiredLevel  int32                  `protobuf:"varint,15,opt,name=required_level,json=requiredLevel,proto3" json:"required_level,omitempty"`
	BaseSellPrice  int32                  `protobuf:"varint,16,opt,name=base_sell_price,json=baseSellPrice,proto3" json:"base_sell_price,omitempty"`
	BaseBuyPrice   int32                  `protobuf:"varint,17,opt,name=base_buy_price,json=baseBuyPrice,proto3" json:"base_buy_price,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WeaponDetail) Reset() {
	*x = WeaponDetail{}
	mi := &file_api_proto_items_items_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeaponDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeaponDetail) ProtoMessage() {}

func (x *WeaponDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_items_items_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeaponDetail.ProtoReflect.Descriptor instead.
func (*WeaponDetail) Descriptor() ([]byte, []int) {
	return file_api_proto_items_items_proto_rawDescGZIP(), []int{1}
}

func (x *WeaponDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WeaponDetail) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *WeaponDetail) GetRarityId() string {
	if x != nil {
		return x.RarityId
	}
	return ""
}

func (x *WeaponDetail) GetAttackPower() int32 {
	if x != nil {
		return x.AttackPower
	}
	return 0
}

func (x *WeaponDetail) GetDurability() int32 {
	if x != nil {
		return x.Durability
	}
	return 0
}

func (x *WeaponDetail) GetCriticalRate() float32 {
	if x != nil {
		return x.CriticalRate
	}
	return 0
}

func (x *WeaponDetail) GetWeaponType() string {
	if x != nil {
		return x.WeaponType
	}
	return ""
}

func (x *WeaponDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WeaponDetail) GetItemTemplateId() string {
	if x != nil {
		return x.ItemTemplateId
	}
	return ""
}

func (x *WeaponDetail) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *WeaponDetail) GetItemCode() string {
	if x != nil {
		return x.ItemCode
	}
	return ""
}

func (x *WeaponDetail) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *WeaponDetail) GetIsTradeable() bool {
	if x != nil {
		return x.IsTradeable
	}
	return false
}

func (x *WeaponDetail) GetIsDroppable() bool {
	if x != nil {
		return x.IsDroppable
	}
	return false
}

func (x *WeaponDetail) GetRequiredLevel() int32 {
	if x != nil {
		return x.RequiredLevel
	}
	return 0
}

func (x *WeaponDetail) GetBaseSellPrice() int32 {
	if x != nil {
		return x.BaseSellPrice
	}
	return 0
}

func (x *WeaponDetail) GetBaseBuyPrice() int32 {
	if x != nil {
		return x.BaseBuyPrice
	}
	return 0
}

func (x *WeaponDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WeaponDetail) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateWeaponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeId        string                 `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	RarityId      string                 `protobuf:"bytes,2,opt,name=rarity_id,json=rarityId,proto3" json:"rarity_id,omitempty"`
	AttackPower   int32                  `protobuf:"varint,3,opt,name=attack_power,json=attackPower,proto3" json:"attack_power,omitempty"`
	Durability    int32                  `protobuf:"varint,4,opt,name=durability,proto3" json:"durability,omitempty"`
	CriticalRate  float32                `protobuf:"fixed32,5,opt,name=critical_rate,json=criticalRate,proto3" json:"critical_rate,omitempty"`
	WeaponType    string                 `protobuf:"bytes,6,opt,name=weapon_type,json=weaponType,proto3" json:"weapon_type,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWeaponRequest) Reset() {
	*x = CreateWeaponRequest{}
	mi := &file_api_proto_items_items_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWeaponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWeaponRequest) ProtoMessage() {}

func (x *CreateWeaponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_items_items_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWeaponRequest.ProtoReflect.Descriptor instead.
func (*CreateWeaponRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_items_items_proto_rawDescGZIP(), []int{2}
}

func (x *CreateWeaponRequest) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *CreateWeaponRequest) GetRarityId() string {
	if x != nil {
		return x.RarityId
	}
	return ""
}

func (x *CreateWeaponRequest) GetAttackPower() int32 {
	if x != nil {
		return x.AttackPower
	}
	return 0
}

func (x *CreateWeaponRequest) GetDurability() int32 {
	if x != nil {
		return x.Durability
	}
	return 0
}

func (x *CreateWeaponRequest) GetCriticalRate() float32 {
	if x != nil {
		return x.CriticalRate
	}
	return 0
}

func (x *CreateWeaponRequest) GetWeaponType() string {
	if x != nil {
		return x.WeaponType
	}
	return ""
}

func (x *CreateWeaponRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetWeaponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeaponRequest) Reset() {
	*x = GetWeaponRequest{}
	mi := &file_api_proto_items_items_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeaponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeaponRequest) ProtoMessage() {}

func (x *GetWeaponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_items_items_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeaponRequest.ProtoReflect.Descriptor instead.
func (*GetWeaponRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_items_items_proto_rawDescGZIP(), []int{3}
}

func (x *GetWeaponRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListWeaponsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weapons       []*WeaponDetail        `protobuf:"bytes,1,rep,name=weapons,proto3" json:"weapons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWeaponsResponse) Reset() {
	*x = ListWeaponsResponse{}
	mi := &file_api_proto_items_items_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWeaponsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWeaponsResponse) ProtoMessage() {}

func (x *ListWeaponsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_items_items_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWeaponsResponse.ProtoReflect.Descriptor instead.
func (*ListWeaponsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_items_items_proto_rawDescGZIP(), []int{4}
}

func (x *ListWeaponsResponse) GetWeapons() []*WeaponDetail {
	if x != nil {
		return x.Weapons
	}
	return nil
}

var File_api_proto_items_items_proto protoreflect.FileDescriptor

const file_api_proto_items_items_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/items/items.proto\x12\x05items\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xef\x02\n" +
	"\x06Weapon\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atype_id\x18\x02 \x01(\tR\x06typeId\x12\x1b\n" +
	"\trarity_id\x18\x03 \x01(\tR\brarityId\x12!\n" +
	"\fattack_power\x18\x04 \x01(\x05R\vattackPower\x12\x1e\n" +
	"\n" +
	"durability\x18\x05 \x01(\x05R\n" +
	"durability\x12#\n" +
	"\rcritical_rate\x18\x06 \x01(\x02R\fcriticalRate\x12\x1f\n" +
	"\vweapon_type\x18\a \x01(\tR\n" +
	"weaponType\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xaf\x05\n" +
	"\fWeaponDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atype_id\x18\x02 \x01(\tR\x06typeId\x12\x1b\n" +
	"\trarity_id\x18\x03 \x01(\tR\brarityId\x12!\n" +
	"\fattack_power\x18\x04 \x01(\x05R\vattackPower\x12\x1e\n" +
	"\n" +
	"durability\x18\x05 \x01(\x05R\n" +
	"durability\x12#\n" +
	"\rcritical_rate\x18\x06 \x01(\x02R\fcriticalRate\x12\x1f\n" +
	"\vweapon_type\x18\a \x01(\tR\n" +
	"weaponType\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12(\n" +
	"\x10item_template_id\x18\t \x01(\tR\x0eitemTemplateId\x12\x1b\n" +
	"\titem_name\x18\n" +
	" \x01(\tR\bitemName\x12\x1b\n" +
	"\titem_code\x18\v \x01(\tR\bitemCode\x12\x19\n" +
	"\bicon_url\x18\f \x01(\tR\aiconUrl\x12!\n" +
	"\fis_tradeable\x18\r \x01(\bR\visTradeable\x12!\n" +
	"\fis_droppable\x18\x0e \x01(\bR\visDroppable\x12%\n" +
	"\x0erequired_level\x18\x0f \x01(\x05R\rrequiredLevel\x12&\n" +
	"\x0fbase_sell_price\x18\x10 \x01(\x05R\rbaseSellPrice\x12$\n" +
	"\x0ebase_buy_price\x18\x11 \x01(\x05R\fbaseBuyPrice\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf6\x01\n" +
	"\x13CreateWeaponRequest\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\tR\x06typeId\x12\x1b\n" +
	"\trarity_id\x18\x02 \x01(\tR\brarityId\x12!\n" +
	"\fattack_power\x18\x03 \x01(\x05R\vattackPower\x12\x1e\n" +
	"\n" +
	"durability\x18\x04 \x01(\x05R\n" +
	"durability\x12#\n" +
	"\rcritical_rate\x18\x05 \x01(\x02R\fcriticalRate\x12\x1f\n" +
	"\vweapon_type\x18\x06 \x01(\tR\n" +
	"weaponType\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"\"\n" +
	"\x10GetWeaponRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x13ListWeaponsResponse\x12-\n" +
	"\aweapons\x18\x01 \x03(\v2\x13.items.WeaponDetailR\aweapons2\xe3\x01\n" +
	"\fItemsService\x129\n" +
	"\fCreateWeapon\x12\x1a.items.CreateWeaponRequest\x1a\r.items.Weapon\x12I\n" +
	"\x19GetWeaponWithTemplateByID\x12\x17.items.GetWeaponRequest\x1a\x13.items.WeaponDetail\x12M\n" +
	"\x17ListWeaponsWithTemplate\x12\x16.google.protobuf.Empty\x1a\x1a.items.ListWeaponsResponseBCZAgithub.com/darkphotonKN/cosmic-void-server/common/api/proto/itemsb\x06proto3"

var (
	file_api_proto_items_items_proto_rawDescOnce sync.Once
	file_api_proto_items_items_proto_rawDescData []byte
)

func file_api_proto_items_items_proto_rawDescGZIP() []byte {
	file_api_proto_items_items_proto_rawDescOnce.Do(func() {
		file_api_proto_items_items_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_items_items_proto_rawDesc), len(file_api_proto_items_items_proto_rawDesc)))
	})
	return file_api_proto_items_items_proto_rawDescData
}

var file_api_proto_items_items_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_items_items_proto_goTypes = []any{
	(*Weapon)(nil),                // 0: items.Weapon
	(*WeaponDetail)(nil),          // 1: items.WeaponDetail
	(*CreateWeaponRequest)(nil),   // 2: items.CreateWeaponRequest
	(*GetWeaponRequest)(nil),      // 3: items.GetWeaponRequest
	(*ListWeaponsResponse)(nil),   // 4: items.ListWeaponsResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_api_proto_items_items_proto_depIdxs = []int32{
	5, // 0: items.Weapon.created_at:type_name -> google.protobuf.Timestamp
	5, // 1: items.Weapon.updated_at:type_name -> google.protobuf.Timestamp
	5, // 2: items.WeaponDetail.created_at:type_name -> google.protobuf.Timestamp
	5, // 3: items.WeaponDetail.updated_at:type_name -> google.protobuf.Timestamp
	1, // 4: items.ListWeaponsResponse.weapons:type_name -> items.WeaponDetail
	2, // 5: items.ItemsService.CreateWeapon:input_type -> items.CreateWeaponRequest
	3, // 6: items.ItemsService.GetWeaponWithTemplateByID:input_type -> items.GetWeaponRequest
	6, // 7: items.ItemsService.ListWeaponsWithTemplate:input_type -> google.protobuf.Empty
	0, // 8: items.ItemsService.CreateWeapon:output_type -> items.Weapon
	1, // 9: items.ItemsService.GetWeaponWithTemplateByID:output_type -> items.WeaponDetail
	4, // 10: items.ItemsService.ListWeaponsWithTemplate:output_type -> items.ListWeaponsResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_items_items_proto_init() }
func file_api_proto_items_items_proto_init() {
	if File_api_proto_items_items_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_items_items_proto_rawDesc), len(file_api_proto_items_items_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_items_items_proto_goTypes,
		DependencyIndexes: file_api_proto_items_items_proto_depIdxs,
		MessageInfos:      file_api_proto_items_items_proto_msgTypes,
	}.Build()
	File_api_proto_items_items_proto = out.File
	file_api_proto_items_items_proto_goTypes = nil
	file_api_proto_items_items_proto_depIdxs = nil
}
