// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/proto/payment/payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateCustomer
type CreateCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerRequest) Reset() {
	*x = CreateCustomerRequest{}
	mi := &file_api_proto_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerRequest) ProtoMessage() {}

func (x *CreateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerRequest.ProtoReflect.Descriptor instead.
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCustomerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCustomerRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerResponse) Reset() {
	*x = CreateCustomerResponse{}
	mi := &file_api_proto_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerResponse) ProtoMessage() {}

func (x *CreateCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerResponse.ProtoReflect.Descriptor instead.
func (*CreateCustomerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCustomerResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

// SetupSubscription - creates a subscription product
type SetupSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"` // in cents
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupSubscriptionRequest) Reset() {
	*x = SetupSubscriptionRequest{}
	mi := &file_api_proto_payment_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupSubscriptionRequest) ProtoMessage() {}

func (x *SetupSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*SetupSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_payment_proto_rawDescGZIP(), []int{2}
}

func (x *SetupSubscriptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetupSubscriptionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SetupSubscriptionRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type SetupSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	PriceId       string                 `protobuf:"bytes,2,opt,name=price_id,json=priceId,proto3" json:"price_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupSubscriptionResponse) Reset() {
	*x = SetupSubscriptionResponse{}
	mi := &file_api_proto_payment_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupSubscriptionResponse) ProtoMessage() {}

func (x *SetupSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*SetupSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_payment_proto_rawDescGZIP(), []int{3}
}

func (x *SetupSubscriptionResponse) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *SetupSubscriptionResponse) GetPriceId() string {
	if x != nil {
		return x.PriceId
	}
	return ""
}

// Subscribe - subscribes a customer to a product
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_proto_payment_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_payment_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *SubscribeRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type SubscribeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	ClientSecret   string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_api_proto_payment_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_payment_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeResponse) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *SubscribeResponse) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *SubscribeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GetUserSubscriptions
type GetUserSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSubscriptionsRequest) Reset() {
	*x = GetUserSubscriptionsRequest{}
	mi := &file_api_proto_payment_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSubscriptionsRequest) ProtoMessage() {}

func (x *GetUserSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_payment_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserSubscriptionsRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type UserSubscriptionInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId   string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	ProductId        string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	PriceId          string                 `protobuf:"bytes,3,opt,name=price_id,json=priceId,proto3" json:"price_id,omitempty"`
	Status           string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CurrentPeriodEnd int64                  `protobuf:"varint,5,opt,name=current_period_end,json=currentPeriodEnd,proto3" json:"current_period_end,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserSubscriptionInfo) Reset() {
	*x = UserSubscriptionInfo{}
	mi := &file_api_proto_payment_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSubscriptionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSubscriptionInfo) ProtoMessage() {}

func (x *UserSubscriptionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSubscriptionInfo.ProtoReflect.Descriptor instead.
func (*UserSubscriptionInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_payment_proto_rawDescGZIP(), []int{7}
}

func (x *UserSubscriptionInfo) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *UserSubscriptionInfo) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UserSubscriptionInfo) GetPriceId() string {
	if x != nil {
		return x.PriceId
	}
	return ""
}

func (x *UserSubscriptionInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserSubscriptionInfo) GetCurrentPeriodEnd() int64 {
	if x != nil {
		return x.CurrentPeriodEnd
	}
	return 0
}

type GetUserSubscriptionsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Subscriptions []*UserSubscriptionInfo `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSubscriptionsResponse) Reset() {
	*x = GetUserSubscriptionsResponse{}
	mi := &file_api_proto_payment_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSubscriptionsResponse) ProtoMessage() {}

func (x *GetUserSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_payment_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserSubscriptionsResponse) GetSubscriptions() []*UserSubscriptionInfo {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

var File_api_proto_payment_payment_proto protoreflect.FileDescriptor

const file_api_proto_payment_payment_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/payment/payment.proto\x12\apayment\"F\n" +
	"\x15CreateCustomerRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"9\n" +
	"\x16CreateCustomerResponse\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\"f\n" +
	"\x18SetupSubscriptionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\"U\n" +
	"\x19SetupSubscriptionResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x19\n" +
	"\bprice_id\x18\x02 \x01(\tR\apriceId\"R\n" +
	"\x10SubscribeRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\"y\n" +
	"\x11SubscribeResponse\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\">\n" +
	"\x1bGetUserSubscriptionsRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\"\xbf\x01\n" +
	"\x14UserSubscriptionInfo\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x19\n" +
	"\bprice_id\x18\x03 \x01(\tR\apriceId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12,\n" +
	"\x12current_period_end\x18\x05 \x01(\x03R\x10currentPeriodEnd\"c\n" +
	"\x1cGetUserSubscriptionsResponse\x12C\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x1d.payment.UserSubscriptionInfoR\rsubscriptions2\xf0\x02\n" +
	"\x0ePaymentService\x12S\n" +
	"\x0eCreateCustomer\x12\x1e.payment.CreateCustomerRequest\x1a\x1f.payment.CreateCustomerResponse\"\x00\x12\\\n" +
	"\x11SetupSubscription\x12!.payment.SetupSubscriptionRequest\x1a\".payment.SetupSubscriptionResponse\"\x00\x12D\n" +
	"\tSubscribe\x12\x19.payment.SubscribeRequest\x1a\x1a.payment.SubscribeResponse\"\x00\x12e\n" +
	"\x14GetUserSubscriptions\x12$.payment.GetUserSubscriptionsRequest\x1a%.payment.GetUserSubscriptionsResponse\"\x00BEZCgithub.com/darkphotonKN/cosmic-void-server/common/api/proto/paymentb\x06proto3"

var (
	file_api_proto_payment_payment_proto_rawDescOnce sync.Once
	file_api_proto_payment_payment_proto_rawDescData []byte
)

func file_api_proto_payment_payment_proto_rawDescGZIP() []byte {
	file_api_proto_payment_payment_proto_rawDescOnce.Do(func() {
		file_api_proto_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_payment_payment_proto_rawDesc), len(file_api_proto_payment_payment_proto_rawDesc)))
	})
	return file_api_proto_payment_payment_proto_rawDescData
}

var file_api_proto_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_payment_payment_proto_goTypes = []any{
	(*CreateCustomerRequest)(nil),        // 0: payment.CreateCustomerRequest
	(*CreateCustomerResponse)(nil),       // 1: payment.CreateCustomerResponse
	(*SetupSubscriptionRequest)(nil),     // 2: payment.SetupSubscriptionRequest
	(*SetupSubscriptionResponse)(nil),    // 3: payment.SetupSubscriptionResponse
	(*SubscribeRequest)(nil),             // 4: payment.SubscribeRequest
	(*SubscribeResponse)(nil),            // 5: payment.SubscribeResponse
	(*GetUserSubscriptionsRequest)(nil),  // 6: payment.GetUserSubscriptionsRequest
	(*UserSubscriptionInfo)(nil),         // 7: payment.UserSubscriptionInfo
	(*GetUserSubscriptionsResponse)(nil), // 8: payment.GetUserSubscriptionsResponse
}
var file_api_proto_payment_payment_proto_depIdxs = []int32{
	7, // 0: payment.GetUserSubscriptionsResponse.subscriptions:type_name -> payment.UserSubscriptionInfo
	0, // 1: payment.PaymentService.CreateCustomer:input_type -> payment.CreateCustomerRequest
	2, // 2: payment.PaymentService.SetupSubscription:input_type -> payment.SetupSubscriptionRequest
	4, // 3: payment.PaymentService.Subscribe:input_type -> payment.SubscribeRequest
	6, // 4: payment.PaymentService.GetUserSubscriptions:input_type -> payment.GetUserSubscriptionsRequest
	1, // 5: payment.PaymentService.CreateCustomer:output_type -> payment.CreateCustomerResponse
	3, // 6: payment.PaymentService.SetupSubscription:output_type -> payment.SetupSubscriptionResponse
	5, // 7: payment.PaymentService.Subscribe:output_type -> payment.SubscribeResponse
	8, // 8: payment.PaymentService.GetUserSubscriptions:output_type -> payment.GetUserSubscriptionsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_payment_payment_proto_init() }
func file_api_proto_payment_payment_proto_init() {
	if File_api_proto_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_payment_payment_proto_rawDesc), len(file_api_proto_payment_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_payment_payment_proto_goTypes,
		DependencyIndexes: file_api_proto_payment_payment_proto_depIdxs,
		MessageInfos:      file_api_proto_payment_payment_proto_msgTypes,
	}.Build()
	File_api_proto_payment_payment_proto = out.File
	file_api_proto_payment_payment_proto_goTypes = nil
	file_api_proto_payment_payment_proto_depIdxs = nil
}
