// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: api/proto/stats/stats.proto

package stats

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StatsService_CreatePlayerMatchStats_FullMethodName   = "/stats.StatsService/CreatePlayerMatchStats"
	StatsService_CreatePlayerRankingStats_FullMethodName = "/stats.StatsService/CreatePlayerRankingStats"
	StatsService_CreateMatchHistory_FullMethodName       = "/stats.StatsService/CreateMatchHistory"
)

// StatsServiceClient is the client API for StatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StatsService provides methods for creating player statistics records
type StatsServiceClient interface {
	// Create a new player match stats record
	CreatePlayerMatchStats(ctx context.Context, in *CreatePlayerMatchStatsRequest, opts ...grpc.CallOption) (*PlayerMatchStats, error)
	// Create a new player ranking stats record
	CreatePlayerRankingStats(ctx context.Context, in *CreatePlayerRankingStatsRequest, opts ...grpc.CallOption) (*PlayerRankingStats, error)
	// Create a new match history record
	CreateMatchHistory(ctx context.Context, in *CreateMatchHistoryRequest, opts ...grpc.CallOption) (*MatchHistory, error)
}

type statsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsServiceClient(cc grpc.ClientConnInterface) StatsServiceClient {
	return &statsServiceClient{cc}
}

func (c *statsServiceClient) CreatePlayerMatchStats(ctx context.Context, in *CreatePlayerMatchStatsRequest, opts ...grpc.CallOption) (*PlayerMatchStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerMatchStats)
	err := c.cc.Invoke(ctx, StatsService_CreatePlayerMatchStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) CreatePlayerRankingStats(ctx context.Context, in *CreatePlayerRankingStatsRequest, opts ...grpc.CallOption) (*PlayerRankingStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerRankingStats)
	err := c.cc.Invoke(ctx, StatsService_CreatePlayerRankingStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) CreateMatchHistory(ctx context.Context, in *CreateMatchHistoryRequest, opts ...grpc.CallOption) (*MatchHistory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchHistory)
	err := c.cc.Invoke(ctx, StatsService_CreateMatchHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsServiceServer is the server API for StatsService service.
// All implementations must embed UnimplementedStatsServiceServer
// for forward compatibility.
//
// StatsService provides methods for creating player statistics records
type StatsServiceServer interface {
	// Create a new player match stats record
	CreatePlayerMatchStats(context.Context, *CreatePlayerMatchStatsRequest) (*PlayerMatchStats, error)
	// Create a new player ranking stats record
	CreatePlayerRankingStats(context.Context, *CreatePlayerRankingStatsRequest) (*PlayerRankingStats, error)
	// Create a new match history record
	CreateMatchHistory(context.Context, *CreateMatchHistoryRequest) (*MatchHistory, error)
	mustEmbedUnimplementedStatsServiceServer()
}

// UnimplementedStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatsServiceServer struct{}

func (UnimplementedStatsServiceServer) CreatePlayerMatchStats(context.Context, *CreatePlayerMatchStatsRequest) (*PlayerMatchStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlayerMatchStats not implemented")
}
func (UnimplementedStatsServiceServer) CreatePlayerRankingStats(context.Context, *CreatePlayerRankingStatsRequest) (*PlayerRankingStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlayerRankingStats not implemented")
}
func (UnimplementedStatsServiceServer) CreateMatchHistory(context.Context, *CreateMatchHistoryRequest) (*MatchHistory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMatchHistory not implemented")
}
func (UnimplementedStatsServiceServer) mustEmbedUnimplementedStatsServiceServer() {}
func (UnimplementedStatsServiceServer) testEmbeddedByValue()                      {}

// UnsafeStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatsServiceServer will
// result in compilation errors.
type UnsafeStatsServiceServer interface {
	mustEmbedUnimplementedStatsServiceServer()
}

func RegisterStatsServiceServer(s grpc.ServiceRegistrar, srv StatsServiceServer) {
	// If the following call pancis, it indicates UnimplementedStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StatsService_ServiceDesc, srv)
}

func _StatsService_CreatePlayerMatchStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlayerMatchStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).CreatePlayerMatchStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_CreatePlayerMatchStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).CreatePlayerMatchStats(ctx, req.(*CreatePlayerMatchStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_CreatePlayerRankingStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlayerRankingStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).CreatePlayerRankingStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_CreatePlayerRankingStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).CreatePlayerRankingStats(ctx, req.(*CreatePlayerRankingStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_CreateMatchHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMatchHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).CreateMatchHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_CreateMatchHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).CreateMatchHistory(ctx, req.(*CreateMatchHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatsService_ServiceDesc is the grpc.ServiceDesc for StatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stats.StatsService",
	HandlerType: (*StatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePlayerMatchStats",
			Handler:    _StatsService_CreatePlayerMatchStats_Handler,
		},
		{
			MethodName: "CreatePlayerRankingStats",
			Handler:    _StatsService_CreatePlayerRankingStats_Handler,
		},
		{
			MethodName: "CreateMatchHistory",
			Handler:    _StatsService_CreateMatchHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/stats/stats.proto",
}
