// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/proto/stats/stats.proto

package stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPlayerMatchStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerMatchStatsRequest) Reset() {
	*x = GetPlayerMatchStatsRequest{}
	mi := &file_api_proto_stats_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerMatchStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerMatchStatsRequest) ProtoMessage() {}

func (x *GetPlayerMatchStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stats_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerMatchStatsRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerMatchStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_stats_stats_proto_rawDescGZIP(), []int{0}
}

func (x *GetPlayerMatchStatsRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type PlayerMatchStats struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MemberId            string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	GamesPlayed         int32                  `protobuf:"varint,3,opt,name=games_played,json=gamesPlayed,proto3" json:"games_played,omitempty"`
	Wins                int32                  `protobuf:"varint,4,opt,name=wins,proto3" json:"wins,omitempty"`
	Losses              int32                  `protobuf:"varint,5,opt,name=losses,proto3" json:"losses,omitempty"`
	Kills               int32                  `protobuf:"varint,6,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths              int32                  `protobuf:"varint,7,opt,name=deaths,proto3" json:"deaths,omitempty"`
	TimesPlacedTopThree int32                  `protobuf:"varint,8,opt,name=times_placed_top_three,json=timesPlacedTopThree,proto3" json:"times_placed_top_three,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PlayerMatchStats) Reset() {
	*x = PlayerMatchStats{}
	mi := &file_api_proto_stats_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMatchStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMatchStats) ProtoMessage() {}

func (x *PlayerMatchStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stats_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMatchStats.ProtoReflect.Descriptor instead.
func (*PlayerMatchStats) Descriptor() ([]byte, []int) {
	return file_api_proto_stats_stats_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerMatchStats) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerMatchStats) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *PlayerMatchStats) GetGamesPlayed() int32 {
	if x != nil {
		return x.GamesPlayed
	}
	return 0
}

func (x *PlayerMatchStats) GetWins() int32 {
	if x != nil {
		return x.Wins
	}
	return 0
}

func (x *PlayerMatchStats) GetLosses() int32 {
	if x != nil {
		return x.Losses
	}
	return 0
}

func (x *PlayerMatchStats) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *PlayerMatchStats) GetDeaths() int32 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *PlayerMatchStats) GetTimesPlacedTopThree() int32 {
	if x != nil {
		return x.TimesPlacedTopThree
	}
	return 0
}

func (x *PlayerMatchStats) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PlayerMatchStats) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetPlayerRankingStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerRankingStatsRequest) Reset() {
	*x = GetPlayerRankingStatsRequest{}
	mi := &file_api_proto_stats_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerRankingStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerRankingStatsRequest) ProtoMessage() {}

func (x *GetPlayerRankingStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stats_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerRankingStatsRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerRankingStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_stats_stats_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlayerRankingStatsRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type PlayerRankingStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MemberId         string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Username         string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Wins             int32                  `protobuf:"varint,4,opt,name=wins,proto3" json:"wins,omitempty"`
	TopThrees        int32                  `protobuf:"varint,5,opt,name=top_threes,json=topThrees,proto3" json:"top_threes,omitempty"`
	Rating           int32                  `protobuf:"varint,6,opt,name=rating,proto3" json:"rating,omitempty"`
	RankPosition     *int32                 `protobuf:"varint,7,opt,name=rank_position,json=rankPosition,proto3,oneof" json:"rank_position,omitempty"`
	LastCalculatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_calculated_at,json=lastCalculatedAt,proto3" json:"last_calculated_at,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlayerRankingStats) Reset() {
	*x = PlayerRankingStats{}
	mi := &file_api_proto_stats_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRankingStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRankingStats) ProtoMessage() {}

func (x *PlayerRankingStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stats_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRankingStats.ProtoReflect.Descriptor instead.
func (*PlayerRankingStats) Descriptor() ([]byte, []int) {
	return file_api_proto_stats_stats_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerRankingStats) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerRankingStats) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *PlayerRankingStats) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerRankingStats) GetWins() int32 {
	if x != nil {
		return x.Wins
	}
	return 0
}

func (x *PlayerRankingStats) GetTopThrees() int32 {
	if x != nil {
		return x.TopThrees
	}
	return 0
}

func (x *PlayerRankingStats) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *PlayerRankingStats) GetRankPosition() int32 {
	if x != nil && x.RankPosition != nil {
		return *x.RankPosition
	}
	return 0
}

func (x *PlayerRankingStats) GetLastCalculatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCalculatedAt
	}
	return nil
}

func (x *PlayerRankingStats) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PlayerRankingStats) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetMatchHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Limit         *int32                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchHistoryRequest) Reset() {
	*x = GetMatchHistoryRequest{}
	mi := &file_api_proto_stats_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchHistoryRequest) ProtoMessage() {}

func (x *GetMatchHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stats_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetMatchHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_stats_stats_proto_rawDescGZIP(), []int{4}
}

func (x *GetMatchHistoryRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *GetMatchHistoryRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetMatchHistoryRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type GetMatchHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*MatchHistory        `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchHistoryResponse) Reset() {
	*x = GetMatchHistoryResponse{}
	mi := &file_api_proto_stats_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchHistoryResponse) ProtoMessage() {}

func (x *GetMatchHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stats_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetMatchHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_stats_stats_proto_rawDescGZIP(), []int{5}
}

func (x *GetMatchHistoryResponse) GetMatches() []*MatchHistory {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *GetMatchHistoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type MatchHistory struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId      string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MemberId       string                 `protobuf:"bytes,3,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Win            bool                   `protobuf:"varint,4,opt,name=win,proto3" json:"win,omitempty"`
	FinalPosition  int32                  `protobuf:"varint,5,opt,name=final_position,json=finalPosition,proto3" json:"final_position,omitempty"`
	Kills          int32                  `protobuf:"varint,6,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths         int32                  `protobuf:"varint,7,opt,name=deaths,proto3" json:"deaths,omitempty"`
	RatingBefore   *int32                 `protobuf:"varint,8,opt,name=rating_before,json=ratingBefore,proto3,oneof" json:"rating_before,omitempty"`
	RatingAfter    *int32                 `protobuf:"varint,9,opt,name=rating_after,json=ratingAfter,proto3,oneof" json:"rating_after,omitempty"`
	RatingChange   *int32                 `protobuf:"varint,10,opt,name=rating_change,json=ratingChange,proto3,oneof" json:"rating_change,omitempty"`
	MatchStartedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=match_started_at,json=matchStartedAt,proto3" json:"match_started_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MatchHistory) Reset() {
	*x = MatchHistory{}
	mi := &file_api_proto_stats_stats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchHistory) ProtoMessage() {}

func (x *MatchHistory) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stats_stats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchHistory.ProtoReflect.Descriptor instead.
func (*MatchHistory) Descriptor() ([]byte, []int) {
	return file_api_proto_stats_stats_proto_rawDescGZIP(), []int{6}
}

func (x *MatchHistory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MatchHistory) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MatchHistory) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *MatchHistory) GetWin() bool {
	if x != nil {
		return x.Win
	}
	return false
}

func (x *MatchHistory) GetFinalPosition() int32 {
	if x != nil {
		return x.FinalPosition
	}
	return 0
}

func (x *MatchHistory) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *MatchHistory) GetDeaths() int32 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *MatchHistory) GetRatingBefore() int32 {
	if x != nil && x.RatingBefore != nil {
		return *x.RatingBefore
	}
	return 0
}

func (x *MatchHistory) GetRatingAfter() int32 {
	if x != nil && x.RatingAfter != nil {
		return *x.RatingAfter
	}
	return 0
}

func (x *MatchHistory) GetRatingChange() int32 {
	if x != nil && x.RatingChange != nil {
		return *x.RatingChange
	}
	return 0
}

func (x *MatchHistory) GetMatchStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MatchStartedAt
	}
	return nil
}

func (x *MatchHistory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         *int32                 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardRequest) Reset() {
	*x = GetLeaderboardRequest{}
	mi := &file_api_proto_stats_stats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardRequest) ProtoMessage() {}

func (x *GetLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stats_stats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_stats_stats_proto_rawDescGZIP(), []int{7}
}

func (x *GetLeaderboardRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetLeaderboardRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type GetLeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*PlayerRankingStats  `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardResponse) Reset() {
	*x = GetLeaderboardResponse{}
	mi := &file_api_proto_stats_stats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardResponse) ProtoMessage() {}

func (x *GetLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stats_stats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_stats_stats_proto_rawDescGZIP(), []int{8}
}

func (x *GetLeaderboardResponse) GetPlayers() []*PlayerRankingStats {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GetLeaderboardResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_api_proto_stats_stats_proto protoreflect.FileDescriptor

const file_api_proto_stats_stats_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/stats/stats.proto\x12\x05stats\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n" +
	"\x1aGetPlayerMatchStatsRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\"\xe7\x02\n" +
	"\x10PlayerMatchStats\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12!\n" +
	"\fgames_played\x18\x03 \x01(\x05R\vgamesPlayed\x12\x12\n" +
	"\x04wins\x18\x04 \x01(\x05R\x04wins\x12\x16\n" +
	"\x06losses\x18\x05 \x01(\x05R\x06losses\x12\x14\n" +
	"\x05kills\x18\x06 \x01(\x05R\x05kills\x12\x16\n" +
	"\x06deaths\x18\a \x01(\x05R\x06deaths\x123\n" +
	"\x16times_placed_top_three\x18\b \x01(\x05R\x13timesPlacedTopThree\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\";\n" +
	"\x1cGetPlayerRankingStatsRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\"\xa4\x03\n" +
	"\x12PlayerRankingStats\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x12\n" +
	"\x04wins\x18\x04 \x01(\x05R\x04wins\x12\x1d\n" +
	"\n" +
	"top_threes\x18\x05 \x01(\x05R\ttopThrees\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x05R\x06rating\x12(\n" +
	"\rrank_position\x18\a \x01(\x05H\x00R\frankPosition\x88\x01\x01\x12H\n" +
	"\x12last_calculated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x10lastCalculatedAt\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x10\n" +
	"\x0e_rank_position\"\x82\x01\n" +
	"\x16GetMatchHistoryRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x03 \x01(\x05H\x01R\x06offset\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"i\n" +
	"\x17GetMatchHistoryResponse\x12-\n" +
	"\amatches\x18\x01 \x03(\v2\x13.stats.MatchHistoryR\amatches\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xf3\x03\n" +
	"\fMatchHistory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tmember_id\x18\x03 \x01(\tR\bmemberId\x12\x10\n" +
	"\x03win\x18\x04 \x01(\bR\x03win\x12%\n" +
	"\x0efinal_position\x18\x05 \x01(\x05R\rfinalPosition\x12\x14\n" +
	"\x05kills\x18\x06 \x01(\x05R\x05kills\x12\x16\n" +
	"\x06deaths\x18\a \x01(\x05R\x06deaths\x12(\n" +
	"\rrating_before\x18\b \x01(\x05H\x00R\fratingBefore\x88\x01\x01\x12&\n" +
	"\frating_after\x18\t \x01(\x05H\x01R\vratingAfter\x88\x01\x01\x12(\n" +
	"\rrating_change\x18\n" +
	" \x01(\x05H\x02R\fratingChange\x88\x01\x01\x12D\n" +
	"\x10match_started_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x0ematchStartedAt\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x10\n" +
	"\x0e_rating_beforeB\x0f\n" +
	"\r_rating_afterB\x10\n" +
	"\x0e_rating_change\"d\n" +
	"\x15GetLeaderboardRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\x05H\x01R\x06offset\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"n\n" +
	"\x16GetLeaderboardResponse\x123\n" +
	"\aplayers\x18\x01 \x03(\v2\x19.stats.PlayerRankingStatsR\aplayers\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount2\xdb\x02\n" +
	"\fStatsService\x12Q\n" +
	"\x13GetPlayerMatchStats\x12!.stats.GetPlayerMatchStatsRequest\x1a\x17.stats.PlayerMatchStats\x12W\n" +
	"\x15GetPlayerRankingStats\x12#.stats.GetPlayerRankingStatsRequest\x1a\x19.stats.PlayerRankingStats\x12P\n" +
	"\x0fGetMatchHistory\x12\x1d.stats.GetMatchHistoryRequest\x1a\x1e.stats.GetMatchHistoryResponse\x12M\n" +
	"\x0eGetLeaderboard\x12\x1c.stats.GetLeaderboardRequest\x1a\x1d.stats.GetLeaderboardResponseBCZAgithub.com/darkphotonKN/cosmic-void-server/common/api/proto/statsb\x06proto3"

var (
	file_api_proto_stats_stats_proto_rawDescOnce sync.Once
	file_api_proto_stats_stats_proto_rawDescData []byte
)

func file_api_proto_stats_stats_proto_rawDescGZIP() []byte {
	file_api_proto_stats_stats_proto_rawDescOnce.Do(func() {
		file_api_proto_stats_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_stats_stats_proto_rawDesc), len(file_api_proto_stats_stats_proto_rawDesc)))
	})
	return file_api_proto_stats_stats_proto_rawDescData
}

var file_api_proto_stats_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_stats_stats_proto_goTypes = []any{
	(*GetPlayerMatchStatsRequest)(nil),   // 0: stats.GetPlayerMatchStatsRequest
	(*PlayerMatchStats)(nil),             // 1: stats.PlayerMatchStats
	(*GetPlayerRankingStatsRequest)(nil), // 2: stats.GetPlayerRankingStatsRequest
	(*PlayerRankingStats)(nil),           // 3: stats.PlayerRankingStats
	(*GetMatchHistoryRequest)(nil),       // 4: stats.GetMatchHistoryRequest
	(*GetMatchHistoryResponse)(nil),      // 5: stats.GetMatchHistoryResponse
	(*MatchHistory)(nil),                 // 6: stats.MatchHistory
	(*GetLeaderboardRequest)(nil),        // 7: stats.GetLeaderboardRequest
	(*GetLeaderboardResponse)(nil),       // 8: stats.GetLeaderboardResponse
	(*timestamppb.Timestamp)(nil),        // 9: google.protobuf.Timestamp
}
var file_api_proto_stats_stats_proto_depIdxs = []int32{
	9,  // 0: stats.PlayerMatchStats.created_at:type_name -> google.protobuf.Timestamp
	9,  // 1: stats.PlayerMatchStats.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 2: stats.PlayerRankingStats.last_calculated_at:type_name -> google.protobuf.Timestamp
	9,  // 3: stats.PlayerRankingStats.created_at:type_name -> google.protobuf.Timestamp
	9,  // 4: stats.PlayerRankingStats.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 5: stats.GetMatchHistoryResponse.matches:type_name -> stats.MatchHistory
	9,  // 6: stats.MatchHistory.match_started_at:type_name -> google.protobuf.Timestamp
	9,  // 7: stats.MatchHistory.created_at:type_name -> google.protobuf.Timestamp
	3,  // 8: stats.GetLeaderboardResponse.players:type_name -> stats.PlayerRankingStats
	0,  // 9: stats.StatsService.GetPlayerMatchStats:input_type -> stats.GetPlayerMatchStatsRequest
	2,  // 10: stats.StatsService.GetPlayerRankingStats:input_type -> stats.GetPlayerRankingStatsRequest
	4,  // 11: stats.StatsService.GetMatchHistory:input_type -> stats.GetMatchHistoryRequest
	7,  // 12: stats.StatsService.GetLeaderboard:input_type -> stats.GetLeaderboardRequest
	1,  // 13: stats.StatsService.GetPlayerMatchStats:output_type -> stats.PlayerMatchStats
	3,  // 14: stats.StatsService.GetPlayerRankingStats:output_type -> stats.PlayerRankingStats
	5,  // 15: stats.StatsService.GetMatchHistory:output_type -> stats.GetMatchHistoryResponse
	8,  // 16: stats.StatsService.GetLeaderboard:output_type -> stats.GetLeaderboardResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_stats_stats_proto_init() }
func file_api_proto_stats_stats_proto_init() {
	if File_api_proto_stats_stats_proto != nil {
		return
	}
	file_api_proto_stats_stats_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_proto_stats_stats_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_proto_stats_stats_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_proto_stats_stats_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_stats_stats_proto_rawDesc), len(file_api_proto_stats_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_stats_stats_proto_goTypes,
		DependencyIndexes: file_api_proto_stats_stats_proto_depIdxs,
		MessageInfos:      file_api_proto_stats_stats_proto_msgTypes,
	}.Build()
	File_api_proto_stats_stats_proto = out.File
	file_api_proto_stats_stats_proto_goTypes = nil
	file_api_proto_stats_stats_proto_depIdxs = nil
}
