syntax = "proto3";
package notification;

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/struct.proto";
option go_package = "github.com/darkphotonKN/cosmic-void-server/common/api/proto/notification";

// NotificationService external API for notification

service NotificationService {
  rpc GetNotification(NotificationRequest) returns (NotificationResponse);
}

message NotificationRequest {
  string user_id = 1;
  optional int32 limit = 2;
  optional int32 offset = 3;
}

message NotificationList {
  string id = 1;
  string user_id = 2;
  string title = 3;
  string message = 4;
  string notification_type = 5;  // 'game', 'achievement', 'system', 'friend'
  string event_type = 6;  // 'member.signedup', 'item.created', 'match.ended'
  bool read = 7;
  google.protobuf.Struct data = 8;
  google.protobuf.Timestamp created_at = 9;
  google.protobuf.Timestamp updated_at = 10;
}

message NotificationResponse {
    repeated NotificationList notifications = 1;
    int32 total = 2;
    int32 unread_count = 3;
}
