// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/proto/notification/notification.proto

package notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         *int32                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationRequest) Reset() {
	*x = NotificationRequest{}
	mi := &file_api_proto_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRequest) ProtoMessage() {}

func (x *NotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationRequest.ProtoReflect.Descriptor instead.
func (*NotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotificationRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *NotificationRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type NotificationList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationList) Reset() {
	*x = NotificationList{}
	mi := &file_api_proto_notification_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationList) ProtoMessage() {}

func (x *NotificationList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notification_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationList.ProtoReflect.Descriptor instead.
func (*NotificationList) Descriptor() ([]byte, []int) {
	return file_api_proto_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationList) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotificationList) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationList) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotificationList) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type NotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*NotificationList    `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationResponse) Reset() {
	*x = NotificationResponse{}
	mi := &file_api_proto_notification_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResponse) ProtoMessage() {}

func (x *NotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_notification_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResponse.ProtoReflect.Descriptor instead.
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_notification_notification_proto_rawDescGZIP(), []int{2}
}

func (x *NotificationResponse) GetNotifications() []*NotificationList {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *NotificationResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_api_proto_notification_notification_proto protoreflect.FileDescriptor

const file_api_proto_notification_notification_proto_rawDesc = "" +
	"\n" +
	")api/proto/notification/notification.proto\x12\fnotification\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"{\n" +
	"\x13NotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x03 \x01(\x05H\x01R\x06offset\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"\x88\x01\n" +
	"\x10NotificationList\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04data\"r\n" +
	"\x14NotificationResponse\x12D\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1e.notification.NotificationListR\rnotifications\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2o\n" +
	"\x13NotificationService\x12X\n" +
	"\x0fGetNotification\x12!.notification.NotificationRequest\x1a\".notification.NotificationResponseBJZHgithub.com/darkphotonKN/cosmic-void-server/common/api/proto/notificationb\x06proto3"

var (
	file_api_proto_notification_notification_proto_rawDescOnce sync.Once
	file_api_proto_notification_notification_proto_rawDescData []byte
)

func file_api_proto_notification_notification_proto_rawDescGZIP() []byte {
	file_api_proto_notification_notification_proto_rawDescOnce.Do(func() {
		file_api_proto_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_notification_notification_proto_rawDesc), len(file_api_proto_notification_notification_proto_rawDesc)))
	})
	return file_api_proto_notification_notification_proto_rawDescData
}

var file_api_proto_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_notification_notification_proto_goTypes = []any{
	(*NotificationRequest)(nil),  // 0: notification.NotificationRequest
	(*NotificationList)(nil),     // 1: notification.NotificationList
	(*NotificationResponse)(nil), // 2: notification.NotificationResponse
	(*structpb.Struct)(nil),      // 3: google.protobuf.Struct
}
var file_api_proto_notification_notification_proto_depIdxs = []int32{
	3, // 0: notification.NotificationList.data:type_name -> google.protobuf.Struct
	1, // 1: notification.NotificationResponse.notifications:type_name -> notification.NotificationList
	0, // 2: notification.NotificationService.GetNotification:input_type -> notification.NotificationRequest
	2, // 3: notification.NotificationService.GetNotification:output_type -> notification.NotificationResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_notification_notification_proto_init() }
func file_api_proto_notification_notification_proto_init() {
	if File_api_proto_notification_notification_proto != nil {
		return
	}
	file_api_proto_notification_notification_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_notification_notification_proto_rawDesc), len(file_api_proto_notification_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_notification_notification_proto_goTypes,
		DependencyIndexes: file_api_proto_notification_notification_proto_depIdxs,
		MessageInfos:      file_api_proto_notification_notification_proto_msgTypes,
	}.Build()
	File_api_proto_notification_notification_proto = out.File
	file_api_proto_notification_notification_proto_goTypes = nil
	file_api_proto_notification_notification_proto_depIdxs = nil
}
