// auth-service/proto/auth.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/proto/auth/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Member message represents a user in the system
type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	AverageRating float32                `protobuf:"fixed32,5,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,8,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Member) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Member) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Member) GetAverageRating() float32 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *Member) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Member) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Member) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

// Login request
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Login response with tokens
type LoginResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccessToken      string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken     string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessExpiresIn  int32                  `protobuf:"varint,3,opt,name=access_expires_in,json=accessExpiresIn,proto3" json:"access_expires_in,omitempty"`
	RefreshExpiresIn int32                  `protobuf:"varint,4,opt,name=refresh_expires_in,json=refreshExpiresIn,proto3" json:"refresh_expires_in,omitempty"`
	MemberInfo       *Member                `protobuf:"bytes,5,opt,name=member_info,json=memberInfo,proto3" json:"member_info,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetAccessExpiresIn() int32 {
	if x != nil {
		return x.AccessExpiresIn
	}
	return 0
}

func (x *LoginResponse) GetRefreshExpiresIn() int32 {
	if x != nil {
		return x.RefreshExpiresIn
	}
	return 0
}

func (x *LoginResponse) GetMemberInfo() *Member {
	if x != nil {
		return x.MemberInfo
	}
	return nil
}

// Get member request
type GetMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberRequest) Reset() {
	*x = GetMemberRequest{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberRequest) ProtoMessage() {}

func (x *GetMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberRequest.ProtoReflect.Descriptor instead.
func (*GetMemberRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *GetMemberRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Create member request
type CreateMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemberRequest) Reset() {
	*x = CreateMemberRequest{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemberRequest) ProtoMessage() {}

func (x *CreateMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemberRequest.ProtoReflect.Descriptor instead.
func (*CreateMemberRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMemberRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMemberRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateMemberRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Update member info request
type UpdateMemberInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberInfoRequest) Reset() {
	*x = UpdateMemberInfoRequest{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberInfoRequest) ProtoMessage() {}

func (x *UpdateMemberInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemberInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMemberInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMemberInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMemberInfoRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Update password request
type UpdatePasswordRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CurrentPassword   string                 `protobuf:"bytes,2,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	NewPassword       string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	RepeatNewPassword string                 `protobuf:"bytes,4,opt,name=repeat_new_password,json=repeatNewPassword,proto3" json:"repeat_new_password,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdatePasswordRequest) Reset() {
	*x = UpdatePasswordRequest{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRequest) ProtoMessage() {}

func (x *UpdatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePasswordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePasswordRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

func (x *UpdatePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *UpdatePasswordRequest) GetRepeatNewPassword() string {
	if x != nil {
		return x.RepeatNewPassword
	}
	return ""
}

// Update password response
type UpdatePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordResponse) Reset() {
	*x = UpdatePasswordResponse{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordResponse) ProtoMessage() {}

func (x *UpdatePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordResponse.ProtoReflect.Descriptor instead.
func (*UpdatePasswordResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdatePasswordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Validate token request
type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Validate token response
type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

// Set Stripe customer ID request
type SetStripeCustomerIDRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MemberId         string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	StripeCustomerId string                 `protobuf:"bytes,2,opt,name=stripe_customer_id,json=stripeCustomerId,proto3" json:"stripe_customer_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetStripeCustomerIDRequest) Reset() {
	*x = SetStripeCustomerIDRequest{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStripeCustomerIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStripeCustomerIDRequest) ProtoMessage() {}

func (x *SetStripeCustomerIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStripeCustomerIDRequest.ProtoReflect.Descriptor instead.
func (*SetStripeCustomerIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{10}
}

func (x *SetStripeCustomerIDRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *SetStripeCustomerIDRequest) GetStripeCustomerId() string {
	if x != nil {
		return x.StripeCustomerId
	}
	return ""
}

// Set Stripe customer ID response
type SetStripeCustomerIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStripeCustomerIDResponse) Reset() {
	*x = SetStripeCustomerIDResponse{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStripeCustomerIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStripeCustomerIDResponse) ProtoMessage() {}

func (x *SetStripeCustomerIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStripeCustomerIDResponse.ProtoReflect.Descriptor instead.
func (*SetStripeCustomerIDResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{11}
}

func (x *SetStripeCustomerIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Get Stripe customer ID request
type GetStripeCustomerIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStripeCustomerIDRequest) Reset() {
	*x = GetStripeCustomerIDRequest{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStripeCustomerIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStripeCustomerIDRequest) ProtoMessage() {}

func (x *GetStripeCustomerIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStripeCustomerIDRequest.ProtoReflect.Descriptor instead.
func (*GetStripeCustomerIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{12}
}

func (x *GetStripeCustomerIDRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

// Get Stripe customer ID response
type GetStripeCustomerIDResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StripeCustomerId string                 `protobuf:"bytes,1,opt,name=stripe_customer_id,json=stripeCustomerId,proto3" json:"stripe_customer_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetStripeCustomerIDResponse) Reset() {
	*x = GetStripeCustomerIDResponse{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStripeCustomerIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStripeCustomerIDResponse) ProtoMessage() {}

func (x *GetStripeCustomerIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStripeCustomerIDResponse.ProtoReflect.Descriptor instead.
func (*GetStripeCustomerIDResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{13}
}

func (x *GetStripeCustomerIDResponse) GetStripeCustomerId() string {
	if x != nil {
		return x.StripeCustomerId
	}
	return ""
}

// Request avatar upload request
type RequestAvatarUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAvatarUploadRequest) Reset() {
	*x = RequestAvatarUploadRequest{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAvatarUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAvatarUploadRequest) ProtoMessage() {}

func (x *RequestAvatarUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAvatarUploadRequest.ProtoReflect.Descriptor instead.
func (*RequestAvatarUploadRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{14}
}

func (x *RequestAvatarUploadRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *RequestAvatarUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// Request avatar upload response
type RequestAvatarUploadResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UploadId            string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	PresignedUrl        string                 `protobuf:"bytes,2,opt,name=presigned_url,json=presignedUrl,proto3" json:"presigned_url,omitempty"`
	S3Key               string                 `protobuf:"bytes,3,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"`
	ExpiresAt           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	MaxFileSize         int64                  `protobuf:"varint,5,opt,name=max_file_size,json=maxFileSize,proto3" json:"max_file_size,omitempty"`
	AllowedContentTypes []string               `protobuf:"bytes,6,rep,name=allowed_content_types,json=allowedContentTypes,proto3" json:"allowed_content_types,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RequestAvatarUploadResponse) Reset() {
	*x = RequestAvatarUploadResponse{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAvatarUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAvatarUploadResponse) ProtoMessage() {}

func (x *RequestAvatarUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAvatarUploadResponse.ProtoReflect.Descriptor instead.
func (*RequestAvatarUploadResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{15}
}

func (x *RequestAvatarUploadResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *RequestAvatarUploadResponse) GetPresignedUrl() string {
	if x != nil {
		return x.PresignedUrl
	}
	return ""
}

func (x *RequestAvatarUploadResponse) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

func (x *RequestAvatarUploadResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *RequestAvatarUploadResponse) GetMaxFileSize() int64 {
	if x != nil {
		return x.MaxFileSize
	}
	return 0
}

func (x *RequestAvatarUploadResponse) GetAllowedContentTypes() []string {
	if x != nil {
		return x.AllowedContentTypes
	}
	return nil
}

// Confirm avatar upload request
type ConfirmAvatarUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	UploadId      string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmAvatarUploadRequest) Reset() {
	*x = ConfirmAvatarUploadRequest{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmAvatarUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmAvatarUploadRequest) ProtoMessage() {}

func (x *ConfirmAvatarUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmAvatarUploadRequest.ProtoReflect.Descriptor instead.
func (*ConfirmAvatarUploadRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{16}
}

func (x *ConfirmAvatarUploadRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *ConfirmAvatarUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

// Confirm avatar upload response
type ConfirmAvatarUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmAvatarUploadResponse) Reset() {
	*x = ConfirmAvatarUploadResponse{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmAvatarUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmAvatarUploadResponse) ProtoMessage() {}

func (x *ConfirmAvatarUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmAvatarUploadResponse.ProtoReflect.Descriptor instead.
func (*ConfirmAvatarUploadResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{17}
}

func (x *ConfirmAvatarUploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmAvatarUploadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfirmAvatarUploadResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

var File_api_proto_auth_auth_proto protoreflect.FileDescriptor

const file_api_proto_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/auth/auth.proto\x12\x04auth\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x02\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12%\n" +
	"\x0eaverage_rating\x18\x05 \x01(\x02R\raverageRating\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\b \x01(\tR\tavatarUrl\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xe0\x01\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12*\n" +
	"\x11access_expires_in\x18\x03 \x01(\x05R\x0faccessExpiresIn\x12,\n" +
	"\x12refresh_expires_in\x18\x04 \x01(\x05R\x10refreshExpiresIn\x12-\n" +
	"\vmember_info\x18\x05 \x01(\v2\f.auth.MemberR\n" +
	"memberInfo\"\"\n" +
	"\x10GetMemberRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"[\n" +
	"\x13CreateMemberRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"U\n" +
	"\x17UpdateMemberInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xa5\x01\n" +
	"\x15UpdatePasswordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10current_password\x18\x02 \x01(\tR\x0fcurrentPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\x12.\n" +
	"\x13repeat_new_password\x18\x04 \x01(\tR\x11repeatNewPassword\"L\n" +
	"\x16UpdatePasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"J\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\"g\n" +
	"\x1aSetStripeCustomerIDRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12,\n" +
	"\x12stripe_customer_id\x18\x02 \x01(\tR\x10stripeCustomerId\"7\n" +
	"\x1bSetStripeCustomerIDResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"9\n" +
	"\x1aGetStripeCustomerIDRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\"K\n" +
	"\x1bGetStripeCustomerIDResponse\x12,\n" +
	"\x12stripe_customer_id\x18\x01 \x01(\tR\x10stripeCustomerId\"U\n" +
	"\x1aRequestAvatarUploadRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"\x89\x02\n" +
	"\x1bRequestAvatarUploadResponse\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12#\n" +
	"\rpresigned_url\x18\x02 \x01(\tR\fpresignedUrl\x12\x15\n" +
	"\x06s3_key\x18\x03 \x01(\tR\x05s3Key\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\"\n" +
	"\rmax_file_size\x18\x05 \x01(\x03R\vmaxFileSize\x122\n" +
	"\x15allowed_content_types\x18\x06 \x03(\tR\x13allowedContentTypes\"V\n" +
	"\x1aConfirmAvatarUploadRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\"p\n" +
	"\x1bConfirmAvatarUploadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl2\xd7\x04\n" +
	"\vAuthService\x128\n" +
	"\vLoginMember\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\"\x00\x123\n" +
	"\tGetMember\x12\x16.auth.GetMemberRequest\x1a\f.auth.Member\"\x00\x129\n" +
	"\fCreateMember\x12\x19.auth.CreateMemberRequest\x1a\f.auth.Member\"\x00\x12A\n" +
	"\x10UpdateMemberInfo\x12\x1d.auth.UpdateMemberInfoRequest\x1a\f.auth.Member\"\x00\x12S\n" +
	"\x14UpdateMemberPassword\x12\x1b.auth.UpdatePasswordRequest\x1a\x1c.auth.UpdatePasswordResponse\"\x00\x12J\n" +
	"\rValidateToken\x12\x1a.auth.ValidateTokenRequest\x1a\x1b.auth.ValidateTokenResponse\"\x00\x12\\\n" +
	"\x13SetStripeCustomerID\x12 .auth.SetStripeCustomerIDRequest\x1a!.auth.SetStripeCustomerIDResponse\"\x00\x12\\\n" +
	"\x13GetStripeCustomerID\x12 .auth.GetStripeCustomerIDRequest\x1a!.auth.GetStripeCustomerIDResponse\"\x002\xc7\x01\n" +
	"\rUploadService\x12Z\n" +
	"\x13RequestAvatarUpload\x12 .auth.RequestAvatarUploadRequest\x1a!.auth.RequestAvatarUploadResponse\x12Z\n" +
	"\x13ConfirmAvatarUpload\x12 .auth.ConfirmAvatarUploadRequest\x1a!.auth.ConfirmAvatarUploadResponseBOZMgithub.com/darkphotonKN/community-builds-microservice/auth-service/proto/authb\x06proto3"

var (
	file_api_proto_auth_auth_proto_rawDescOnce sync.Once
	file_api_proto_auth_auth_proto_rawDescData []byte
)

func file_api_proto_auth_auth_proto_rawDescGZIP() []byte {
	file_api_proto_auth_auth_proto_rawDescOnce.Do(func() {
		file_api_proto_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_auth_auth_proto_rawDesc), len(file_api_proto_auth_auth_proto_rawDesc)))
	})
	return file_api_proto_auth_auth_proto_rawDescData
}

var file_api_proto_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_proto_auth_auth_proto_goTypes = []any{
	(*Member)(nil),                      // 0: auth.Member
	(*LoginRequest)(nil),                // 1: auth.LoginRequest
	(*LoginResponse)(nil),               // 2: auth.LoginResponse
	(*GetMemberRequest)(nil),            // 3: auth.GetMemberRequest
	(*CreateMemberRequest)(nil),         // 4: auth.CreateMemberRequest
	(*UpdateMemberInfoRequest)(nil),     // 5: auth.UpdateMemberInfoRequest
	(*UpdatePasswordRequest)(nil),       // 6: auth.UpdatePasswordRequest
	(*UpdatePasswordResponse)(nil),      // 7: auth.UpdatePasswordResponse
	(*ValidateTokenRequest)(nil),        // 8: auth.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),       // 9: auth.ValidateTokenResponse
	(*SetStripeCustomerIDRequest)(nil),  // 10: auth.SetStripeCustomerIDRequest
	(*SetStripeCustomerIDResponse)(nil), // 11: auth.SetStripeCustomerIDResponse
	(*GetStripeCustomerIDRequest)(nil),  // 12: auth.GetStripeCustomerIDRequest
	(*GetStripeCustomerIDResponse)(nil), // 13: auth.GetStripeCustomerIDResponse
	(*RequestAvatarUploadRequest)(nil),  // 14: auth.RequestAvatarUploadRequest
	(*RequestAvatarUploadResponse)(nil), // 15: auth.RequestAvatarUploadResponse
	(*ConfirmAvatarUploadRequest)(nil),  // 16: auth.ConfirmAvatarUploadRequest
	(*ConfirmAvatarUploadResponse)(nil), // 17: auth.ConfirmAvatarUploadResponse
	(*timestamppb.Timestamp)(nil),       // 18: google.protobuf.Timestamp
}
var file_api_proto_auth_auth_proto_depIdxs = []int32{
	18, // 0: auth.Member.created_at:type_name -> google.protobuf.Timestamp
	18, // 1: auth.Member.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: auth.LoginResponse.member_info:type_name -> auth.Member
	18, // 3: auth.RequestAvatarUploadResponse.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 4: auth.AuthService.LoginMember:input_type -> auth.LoginRequest
	3,  // 5: auth.AuthService.GetMember:input_type -> auth.GetMemberRequest
	4,  // 6: auth.AuthService.CreateMember:input_type -> auth.CreateMemberRequest
	5,  // 7: auth.AuthService.UpdateMemberInfo:input_type -> auth.UpdateMemberInfoRequest
	6,  // 8: auth.AuthService.UpdateMemberPassword:input_type -> auth.UpdatePasswordRequest
	8,  // 9: auth.AuthService.ValidateToken:input_type -> auth.ValidateTokenRequest
	10, // 10: auth.AuthService.SetStripeCustomerID:input_type -> auth.SetStripeCustomerIDRequest
	12, // 11: auth.AuthService.GetStripeCustomerID:input_type -> auth.GetStripeCustomerIDRequest
	14, // 12: auth.UploadService.RequestAvatarUpload:input_type -> auth.RequestAvatarUploadRequest
	16, // 13: auth.UploadService.ConfirmAvatarUpload:input_type -> auth.ConfirmAvatarUploadRequest
	2,  // 14: auth.AuthService.LoginMember:output_type -> auth.LoginResponse
	0,  // 15: auth.AuthService.GetMember:output_type -> auth.Member
	0,  // 16: auth.AuthService.CreateMember:output_type -> auth.Member
	0,  // 17: auth.AuthService.UpdateMemberInfo:output_type -> auth.Member
	7,  // 18: auth.AuthService.UpdateMemberPassword:output_type -> auth.UpdatePasswordResponse
	9,  // 19: auth.AuthService.ValidateToken:output_type -> auth.ValidateTokenResponse
	11, // 20: auth.AuthService.SetStripeCustomerID:output_type -> auth.SetStripeCustomerIDResponse
	13, // 21: auth.AuthService.GetStripeCustomerID:output_type -> auth.GetStripeCustomerIDResponse
	15, // 22: auth.UploadService.RequestAvatarUpload:output_type -> auth.RequestAvatarUploadResponse
	17, // 23: auth.UploadService.ConfirmAvatarUpload:output_type -> auth.ConfirmAvatarUploadResponse
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_auth_auth_proto_init() }
func file_api_proto_auth_auth_proto_init() {
	if File_api_proto_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_auth_auth_proto_rawDesc), len(file_api_proto_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_auth_auth_proto_goTypes,
		DependencyIndexes: file_api_proto_auth_auth_proto_depIdxs,
		MessageInfos:      file_api_proto_auth_auth_proto_msgTypes,
	}.Build()
	File_api_proto_auth_auth_proto = out.File
	file_api_proto_auth_auth_proto_goTypes = nil
	file_api_proto_auth_auth_proto_depIdxs = nil
}
