apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: default
  labels:
    app: cosmic-void
    component: auth-service
spec:
  selector:
    matchLabels:
      app: cosmic-void
      component: auth-service
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cosmic-void
        component: auth-service
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: auth-service
        image: cosmic-void/auth-service:dev
        imagePullPolicy: IfNotPresent 
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          tcpSocket:
            port: 7003
          initialDelaySeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 8081
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # TODO: auth-service 還沒實作 /_status/healthz，等補上後再開啟
        env:
        - name: TZ
          value: "Asia/Taipei"
        envFrom:
        - configMapRef:
            name: auth-service-config
        - secretRef:
            name: auth-service-secrets
        ports:
        - containerPort: 7003
          name:  grpc
        - containerPort: 8081
          name: http
      restartPolicy: Always