apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
  labels:
    app: cosmic-void
    component: auth-service
spec:
  type: ClusterIP
  selector:
    app: cosmic-void
    component: auth-service
  ports:
  - name: grpc
    port: 7003
    targetPort: grpc
    protocol: TCP
  - name: http
    port: 8081
    targetPort: http
    protocol: TCP

