// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/proto/events/game.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// events published by game-service
type MatchEndedEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MatchStartedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=match_started_at,json=matchStartedAt,proto3" json:"match_started_at,omitempty"`
	MatchEndedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=match_ended_at,json=matchEndedAt,proto3" json:"match_ended_at,omitempty"`
	Players        []*PlayerMatchResult   `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MatchEndedEvent) Reset() {
	*x = MatchEndedEvent{}
	mi := &file_api_proto_events_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchEndedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchEndedEvent) ProtoMessage() {}

func (x *MatchEndedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchEndedEvent.ProtoReflect.Descriptor instead.
func (*MatchEndedEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_events_game_proto_rawDescGZIP(), []int{0}
}

func (x *MatchEndedEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MatchEndedEvent) GetMatchStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MatchStartedAt
	}
	return nil
}

func (x *MatchEndedEvent) GetMatchEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MatchEndedAt
	}
	return nil
}

func (x *MatchEndedEvent) GetPlayers() []*PlayerMatchResult {
	if x != nil {
		return x.Players
	}
	return nil
}

type PlayerMatchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Win           bool                   `protobuf:"varint,3,opt,name=win,proto3" json:"win,omitempty"`
	FinalPosition int32                  `protobuf:"varint,4,opt,name=final_position,json=finalPosition,proto3" json:"final_position,omitempty"`
	Kills         int32                  `protobuf:"varint,5,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths        int32                  `protobuf:"varint,6,opt,name=deaths,proto3" json:"deaths,omitempty"`
	Escape        bool                   `protobuf:"varint,7,opt,name=escape,proto3" json:"escape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerMatchResult) Reset() {
	*x = PlayerMatchResult{}
	mi := &file_api_proto_events_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMatchResult) ProtoMessage() {}

func (x *PlayerMatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMatchResult.ProtoReflect.Descriptor instead.
func (*PlayerMatchResult) Descriptor() ([]byte, []int) {
	return file_api_proto_events_game_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerMatchResult) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *PlayerMatchResult) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerMatchResult) GetWin() bool {
	if x != nil {
		return x.Win
	}
	return false
}

func (x *PlayerMatchResult) GetFinalPosition() int32 {
	if x != nil {
		return x.FinalPosition
	}
	return 0
}

func (x *PlayerMatchResult) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *PlayerMatchResult) GetDeaths() int32 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *PlayerMatchResult) GetEscape() bool {
	if x != nil {
		return x.Escape
	}
	return false
}

var File_api_proto_events_game_proto protoreflect.FileDescriptor

const file_api_proto_events_game_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/events/game.proto\x12\x06events\x1a\x1fgoogle/protobuf/timestamp.proto\"\xed\x01\n" +
	"\x0fMatchEndedEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12D\n" +
	"\x10match_started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0ematchStartedAt\x12@\n" +
	"\x0ematch_ended_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fmatchEndedAt\x123\n" +
	"\aplayers\x18\x04 \x03(\v2\x19.events.PlayerMatchResultR\aplayers\"\xcb\x01\n" +
	"\x11PlayerMatchResult\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x10\n" +
	"\x03win\x18\x03 \x01(\bR\x03win\x12%\n" +
	"\x0efinal_position\x18\x04 \x01(\x05R\rfinalPosition\x12\x14\n" +
	"\x05kills\x18\x05 \x01(\x05R\x05kills\x12\x16\n" +
	"\x06deaths\x18\x06 \x01(\x05R\x06deaths\x12\x16\n" +
	"\x06escape\x18\a \x01(\bR\x06escapeBDZBgithub.com/darkphotonKN/cosmic-void-server/common/api/proto/eventsb\x06proto3"

var (
	file_api_proto_events_game_proto_rawDescOnce sync.Once
	file_api_proto_events_game_proto_rawDescData []byte
)

func file_api_proto_events_game_proto_rawDescGZIP() []byte {
	file_api_proto_events_game_proto_rawDescOnce.Do(func() {
		file_api_proto_events_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_events_game_proto_rawDesc), len(file_api_proto_events_game_proto_rawDesc)))
	})
	return file_api_proto_events_game_proto_rawDescData
}

var file_api_proto_events_game_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_events_game_proto_goTypes = []any{
	(*MatchEndedEvent)(nil),       // 0: events.MatchEndedEvent
	(*PlayerMatchResult)(nil),     // 1: events.PlayerMatchResult
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_api_proto_events_game_proto_depIdxs = []int32{
	2, // 0: events.MatchEndedEvent.match_started_at:type_name -> google.protobuf.Timestamp
	2, // 1: events.MatchEndedEvent.match_ended_at:type_name -> google.protobuf.Timestamp
	1, // 2: events.MatchEndedEvent.players:type_name -> events.PlayerMatchResult
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_events_game_proto_init() }
func file_api_proto_events_game_proto_init() {
	if File_api_proto_events_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_events_game_proto_rawDesc), len(file_api_proto_events_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_events_game_proto_goTypes,
		DependencyIndexes: file_api_proto_events_game_proto_depIdxs,
		MessageInfos:      file_api_proto_events_game_proto_msgTypes,
	}.Build()
	File_api_proto_events_game_proto = out.File
	file_api_proto_events_game_proto_goTypes = nil
	file_api_proto_events_game_proto_depIdxs = nil
}
