// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/proto/events/game.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// events published by game-service
type MatchEndedEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MatchStartedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=match_started_at,json=matchStartedAt,proto3" json:"match_started_at,omitempty"`
	MatchEndedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=match_ended_at,json=matchEndedAt,proto3" json:"match_ended_at,omitempty"`
	Players        []*PlayerMatchResult   `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MatchEndedEvent) Reset() {
	*x = MatchEndedEvent{}
	mi := &file_api_proto_events_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchEndedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchEndedEvent) ProtoMessage() {}

func (x *MatchEndedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchEndedEvent.ProtoReflect.Descriptor instead.
func (*MatchEndedEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_events_game_proto_rawDescGZIP(), []int{0}
}

func (x *MatchEndedEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MatchEndedEvent) GetMatchStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MatchStartedAt
	}
	return nil
}

func (x *MatchEndedEvent) GetMatchEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MatchEndedAt
	}
	return nil
}

func (x *MatchEndedEvent) GetPlayers() []*PlayerMatchResult {
	if x != nil {
		return x.Players
	}
	return nil
}

type PlayerMatchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Win           bool                   `protobuf:"varint,3,opt,name=win,proto3" json:"win,omitempty"`
	FinalPosition int32                  `protobuf:"varint,4,opt,name=final_position,json=finalPosition,proto3" json:"final_position,omitempty"`
	Kills         int32                  `protobuf:"varint,5,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths        int32                  `protobuf:"varint,6,opt,name=deaths,proto3" json:"deaths,omitempty"`
	Escape        bool                   `protobuf:"varint,7,opt,name=escape,proto3" json:"escape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerMatchResult) Reset() {
	*x = PlayerMatchResult{}
	mi := &file_api_proto_events_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMatchResult) ProtoMessage() {}

func (x *PlayerMatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMatchResult.ProtoReflect.Descriptor instead.
func (*PlayerMatchResult) Descriptor() ([]byte, []int) {
	return file_api_proto_events_game_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerMatchResult) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *PlayerMatchResult) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerMatchResult) GetWin() bool {
	if x != nil {
		return x.Win
	}
	return false
}

func (x *PlayerMatchResult) GetFinalPosition() int32 {
	if x != nil {
		return x.FinalPosition
	}
	return 0
}

func (x *PlayerMatchResult) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *PlayerMatchResult) GetDeaths() int32 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *PlayerMatchResult) GetEscape() bool {
	if x != nil {
		return x.Escape
	}
	return false
}

type ItemsExtractedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	PlayerItems   []*PlayerItems         `protobuf:"bytes,4,rep,name=playerItems,proto3" json:"playerItems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemsExtractedEvent) Reset() {
	*x = ItemsExtractedEvent{}
	mi := &file_api_proto_events_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemsExtractedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemsExtractedEvent) ProtoMessage() {}

func (x *ItemsExtractedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemsExtractedEvent.ProtoReflect.Descriptor instead.
func (*ItemsExtractedEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_events_game_proto_rawDescGZIP(), []int{2}
}

func (x *ItemsExtractedEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ItemsExtractedEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ItemsExtractedEvent) GetPlayerItems() []*PlayerItems {
	if x != nil {
		return x.PlayerItems
	}
	return nil
}

type PlayerItems struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Equipment     *Equipment             `protobuf:"bytes,2,opt,name=equipment,proto3" json:"equipment,omitempty"`
	Inventory     []*Item                `protobuf:"bytes,3,rep,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerItems) Reset() {
	*x = PlayerItems{}
	mi := &file_api_proto_events_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerItems) ProtoMessage() {}

func (x *PlayerItems) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerItems.ProtoReflect.Descriptor instead.
func (*PlayerItems) Descriptor() ([]byte, []int) {
	return file_api_proto_events_game_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerItems) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *PlayerItems) GetEquipment() *Equipment {
	if x != nil {
		return x.Equipment
	}
	return nil
}

func (x *PlayerItems) GetInventory() []*Item {
	if x != nil {
		return x.Inventory
	}
	return nil
}

// All equipment slots — mirrors EquipmentComponent in game-service.
// Each slot holds the full item data (nil when empty).
type Equipment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weapon        *Item                  `protobuf:"bytes,1,opt,name=weapon,proto3" json:"weapon,omitempty"`
	Head          *Item                  `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`
	Chest         *Item                  `protobuf:"bytes,3,opt,name=chest,proto3" json:"chest,omitempty"`
	Gloves        *Item                  `protobuf:"bytes,4,opt,name=gloves,proto3" json:"gloves,omitempty"`
	Legs          *Item                  `protobuf:"bytes,5,opt,name=legs,proto3" json:"legs,omitempty"`
	Ring_1        *Item                  `protobuf:"bytes,6,opt,name=ring_1,json=ring1,proto3" json:"ring_1,omitempty"`
	Ring_2        *Item                  `protobuf:"bytes,7,opt,name=ring_2,json=ring2,proto3" json:"ring_2,omitempty"`
	Consumable_1  *Item                  `protobuf:"bytes,8,opt,name=consumable_1,json=consumable1,proto3" json:"consumable_1,omitempty"`
	Consumable_2  *Item                  `protobuf:"bytes,9,opt,name=consumable_2,json=consumable2,proto3" json:"consumable_2,omitempty"`
	Consumable_3  *Item                  `protobuf:"bytes,10,opt,name=consumable_3,json=consumable3,proto3" json:"consumable_3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Equipment) Reset() {
	*x = Equipment{}
	mi := &file_api_proto_events_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Equipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Equipment) ProtoMessage() {}

func (x *Equipment) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Equipment.ProtoReflect.Descriptor instead.
func (*Equipment) Descriptor() ([]byte, []int) {
	return file_api_proto_events_game_proto_rawDescGZIP(), []int{4}
}

func (x *Equipment) GetWeapon() *Item {
	if x != nil {
		return x.Weapon
	}
	return nil
}

func (x *Equipment) GetHead() *Item {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *Equipment) GetChest() *Item {
	if x != nil {
		return x.Chest
	}
	return nil
}

func (x *Equipment) GetGloves() *Item {
	if x != nil {
		return x.Gloves
	}
	return nil
}

func (x *Equipment) GetLegs() *Item {
	if x != nil {
		return x.Legs
	}
	return nil
}

func (x *Equipment) GetRing_1() *Item {
	if x != nil {
		return x.Ring_1
	}
	return nil
}

func (x *Equipment) GetRing_2() *Item {
	if x != nil {
		return x.Ring_2
	}
	return nil
}

func (x *Equipment) GetConsumable_1() *Item {
	if x != nil {
		return x.Consumable_1
	}
	return nil
}

func (x *Equipment) GetConsumable_2() *Item {
	if x != nil {
		return x.Consumable_2
	}
	return nil
}

func (x *Equipment) GetConsumable_3() *Item {
	if x != nil {
		return x.Consumable_3
	}
	return nil
}

// Single item — carries everything needed to create an item_instances row.
// Maps 1:1 with ItemComponent (game-service) and item_instances table (items-service).
type Item struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TemplateId string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	ItemType   string                 `protobuf:"bytes,2,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"` // "weapon", "armor", "consumable"
	Name       string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Weapon stats
	AttackPower  int32   `protobuf:"varint,4,opt,name=attack_power,json=attackPower,proto3" json:"attack_power,omitempty"`
	CriticalRate float64 `protobuf:"fixed64,5,opt,name=critical_rate,json=criticalRate,proto3" json:"critical_rate,omitempty"`
	WeaponType   string  `protobuf:"bytes,6,opt,name=weapon_type,json=weaponType,proto3" json:"weapon_type,omitempty"`
	// Armor stats
	DefenseRating   int32  `protobuf:"varint,7,opt,name=defense_rating,json=defenseRating,proto3" json:"defense_rating,omitempty"`
	MagicResistance int32  `protobuf:"varint,8,opt,name=magic_resistance,json=magicResistance,proto3" json:"magic_resistance,omitempty"`
	ArmorSlot       string `protobuf:"bytes,9,opt,name=armor_slot,json=armorSlot,proto3" json:"armor_slot,omitempty"` // "head", "chest", "gloves", "legs"
	// Consumable stats
	HealingAmount int32 `protobuf:"varint,10,opt,name=healing_amount,json=healingAmount,proto3" json:"healing_amount,omitempty"`
	ManaAmount    int32 `protobuf:"varint,11,opt,name=mana_amount,json=manaAmount,proto3" json:"mana_amount,omitempty"`
	BuffDuration  int32 `protobuf:"varint,12,opt,name=buff_duration,json=buffDuration,proto3" json:"buff_duration,omitempty"`
	// Shared
	BuyPrice      int32  `protobuf:"varint,13,opt,name=buy_price,json=buyPrice,proto3" json:"buy_price,omitempty"`
	SellPrice     int32  `protobuf:"varint,14,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"`
	Description   string `protobuf:"bytes,15,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_api_proto_events_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_api_proto_events_game_proto_rawDescGZIP(), []int{5}
}

func (x *Item) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *Item) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetAttackPower() int32 {
	if x != nil {
		return x.AttackPower
	}
	return 0
}

func (x *Item) GetCriticalRate() float64 {
	if x != nil {
		return x.CriticalRate
	}
	return 0
}

func (x *Item) GetWeaponType() string {
	if x != nil {
		return x.WeaponType
	}
	return ""
}

func (x *Item) GetDefenseRating() int32 {
	if x != nil {
		return x.DefenseRating
	}
	return 0
}

func (x *Item) GetMagicResistance() int32 {
	if x != nil {
		return x.MagicResistance
	}
	return 0
}

func (x *Item) GetArmorSlot() string {
	if x != nil {
		return x.ArmorSlot
	}
	return ""
}

func (x *Item) GetHealingAmount() int32 {
	if x != nil {
		return x.HealingAmount
	}
	return 0
}

func (x *Item) GetManaAmount() int32 {
	if x != nil {
		return x.ManaAmount
	}
	return 0
}

func (x *Item) GetBuffDuration() int32 {
	if x != nil {
		return x.BuffDuration
	}
	return 0
}

func (x *Item) GetBuyPrice() int32 {
	if x != nil {
		return x.BuyPrice
	}
	return 0
}

func (x *Item) GetSellPrice() int32 {
	if x != nil {
		return x.SellPrice
	}
	return 0
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_api_proto_events_game_proto protoreflect.FileDescriptor

const file_api_proto_events_game_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/events/game.proto\x12\x06events\x1a\x1fgoogle/protobuf/timestamp.proto\"\xed\x01\n" +
	"\x0fMatchEndedEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12D\n" +
	"\x10match_started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0ematchStartedAt\x12@\n" +
	"\x0ematch_ended_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fmatchEndedAt\x123\n" +
	"\aplayers\x18\x04 \x03(\v2\x19.events.PlayerMatchResultR\aplayers\"\xcb\x01\n" +
	"\x11PlayerMatchResult\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x10\n" +
	"\x03win\x18\x03 \x01(\bR\x03win\x12%\n" +
	"\x0efinal_position\x18\x04 \x01(\x05R\rfinalPosition\x12\x14\n" +
	"\x05kills\x18\x05 \x01(\x05R\x05kills\x12\x16\n" +
	"\x06deaths\x18\x06 \x01(\x05R\x06deaths\x12\x16\n" +
	"\x06escape\x18\a \x01(\bR\x06escape\"\x86\x01\n" +
	"\x13ItemsExtractedEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x125\n" +
	"\vplayerItems\x18\x04 \x03(\v2\x13.events.PlayerItemsR\vplayerItems\"\x87\x01\n" +
	"\vPlayerItems\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12/\n" +
	"\tequipment\x18\x02 \x01(\v2\x11.events.EquipmentR\tequipment\x12*\n" +
	"\tinventory\x18\x03 \x03(\v2\f.events.ItemR\tinventory\"\x9c\x03\n" +
	"\tEquipment\x12$\n" +
	"\x06weapon\x18\x01 \x01(\v2\f.events.ItemR\x06weapon\x12 \n" +
	"\x04head\x18\x02 \x01(\v2\f.events.ItemR\x04head\x12\"\n" +
	"\x05chest\x18\x03 \x01(\v2\f.events.ItemR\x05chest\x12$\n" +
	"\x06gloves\x18\x04 \x01(\v2\f.events.ItemR\x06gloves\x12 \n" +
	"\x04legs\x18\x05 \x01(\v2\f.events.ItemR\x04legs\x12#\n" +
	"\x06ring_1\x18\x06 \x01(\v2\f.events.ItemR\x05ring1\x12#\n" +
	"\x06ring_2\x18\a \x01(\v2\f.events.ItemR\x05ring2\x12/\n" +
	"\fconsumable_1\x18\b \x01(\v2\f.events.ItemR\vconsumable1\x12/\n" +
	"\fconsumable_2\x18\t \x01(\v2\f.events.ItemR\vconsumable2\x12/\n" +
	"\fconsumable_3\x18\n" +
	" \x01(\v2\f.events.ItemR\vconsumable3\"\xfd\x03\n" +
	"\x04Item\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x1b\n" +
	"\titem_type\x18\x02 \x01(\tR\bitemType\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fattack_power\x18\x04 \x01(\x05R\vattackPower\x12#\n" +
	"\rcritical_rate\x18\x05 \x01(\x01R\fcriticalRate\x12\x1f\n" +
	"\vweapon_type\x18\x06 \x01(\tR\n" +
	"weaponType\x12%\n" +
	"\x0edefense_rating\x18\a \x01(\x05R\rdefenseRating\x12)\n" +
	"\x10magic_resistance\x18\b \x01(\x05R\x0fmagicResistance\x12\x1d\n" +
	"\n" +
	"armor_slot\x18\t \x01(\tR\tarmorSlot\x12%\n" +
	"\x0ehealing_amount\x18\n" +
	" \x01(\x05R\rhealingAmount\x12\x1f\n" +
	"\vmana_amount\x18\v \x01(\x05R\n" +
	"manaAmount\x12#\n" +
	"\rbuff_duration\x18\f \x01(\x05R\fbuffDuration\x12\x1b\n" +
	"\tbuy_price\x18\r \x01(\x05R\bbuyPrice\x12\x1d\n" +
	"\n" +
	"sell_price\x18\x0e \x01(\x05R\tsellPrice\x12 \n" +
	"\vdescription\x18\x0f \x01(\tR\vdescriptionBDZBgithub.com/darkphotonKN/cosmic-void-server/common/api/proto/eventsb\x06proto3"

var (
	file_api_proto_events_game_proto_rawDescOnce sync.Once
	file_api_proto_events_game_proto_rawDescData []byte
)

func file_api_proto_events_game_proto_rawDescGZIP() []byte {
	file_api_proto_events_game_proto_rawDescOnce.Do(func() {
		file_api_proto_events_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_events_game_proto_rawDesc), len(file_api_proto_events_game_proto_rawDesc)))
	})
	return file_api_proto_events_game_proto_rawDescData
}

var file_api_proto_events_game_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_events_game_proto_goTypes = []any{
	(*MatchEndedEvent)(nil),       // 0: events.MatchEndedEvent
	(*PlayerMatchResult)(nil),     // 1: events.PlayerMatchResult
	(*ItemsExtractedEvent)(nil),   // 2: events.ItemsExtractedEvent
	(*PlayerItems)(nil),           // 3: events.PlayerItems
	(*Equipment)(nil),             // 4: events.Equipment
	(*Item)(nil),                  // 5: events.Item
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_api_proto_events_game_proto_depIdxs = []int32{
	6,  // 0: events.MatchEndedEvent.match_started_at:type_name -> google.protobuf.Timestamp
	6,  // 1: events.MatchEndedEvent.match_ended_at:type_name -> google.protobuf.Timestamp
	1,  // 2: events.MatchEndedEvent.players:type_name -> events.PlayerMatchResult
	3,  // 3: events.ItemsExtractedEvent.playerItems:type_name -> events.PlayerItems
	4,  // 4: events.PlayerItems.equipment:type_name -> events.Equipment
	5,  // 5: events.PlayerItems.inventory:type_name -> events.Item
	5,  // 6: events.Equipment.weapon:type_name -> events.Item
	5,  // 7: events.Equipment.head:type_name -> events.Item
	5,  // 8: events.Equipment.chest:type_name -> events.Item
	5,  // 9: events.Equipment.gloves:type_name -> events.Item
	5,  // 10: events.Equipment.legs:type_name -> events.Item
	5,  // 11: events.Equipment.ring_1:type_name -> events.Item
	5,  // 12: events.Equipment.ring_2:type_name -> events.Item
	5,  // 13: events.Equipment.consumable_1:type_name -> events.Item
	5,  // 14: events.Equipment.consumable_2:type_name -> events.Item
	5,  // 15: events.Equipment.consumable_3:type_name -> events.Item
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_proto_events_game_proto_init() }
func file_api_proto_events_game_proto_init() {
	if File_api_proto_events_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_events_game_proto_rawDesc), len(file_api_proto_events_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_events_game_proto_goTypes,
		DependencyIndexes: file_api_proto_events_game_proto_depIdxs,
		MessageInfos:      file_api_proto_events_game_proto_msgTypes,
	}.Build()
	File_api_proto_events_game_proto = out.File
	file_api_proto_events_game_proto_goTypes = nil
	file_api_proto_events_game_proto_depIdxs = nil
}
