// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: game_state.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Main game state message sent to clients
type ClientGameState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     []byte                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`             // UUID as 16 bytes
	CurrentPlayer *PlayerState           `protobuf:"bytes,2,opt,name=current_player,json=currentPlayer,proto3" json:"current_player,omitempty"` // The recipient player's state
	OtherPlayers  []*PlayerState         `protobuf:"bytes,3,rep,name=other_players,json=otherPlayers,proto3" json:"other_players,omitempty"`    // All other players in the session
	Items         [][]byte               `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`                                      // Item entity IDs as UUIDs (16 bytes each)
	Doors         []*DoorState           `protobuf:"bytes,5,rep,name=doors,proto3" json:"doors,omitempty"`                                      // Door states
	Containers    []*ContainerState      `protobuf:"bytes,6,rep,name=containers,proto3" json:"containers,omitempty"`                            // Container states
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientGameState) Reset() {
	*x = ClientGameState{}
	mi := &file_game_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientGameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientGameState) ProtoMessage() {}

func (x *ClientGameState) ProtoReflect() protoreflect.Message {
	mi := &file_game_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientGameState.ProtoReflect.Descriptor instead.
func (*ClientGameState) Descriptor() ([]byte, []int) {
	return file_game_state_proto_rawDescGZIP(), []int{0}
}

func (x *ClientGameState) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *ClientGameState) GetCurrentPlayer() *PlayerState {
	if x != nil {
		return x.CurrentPlayer
	}
	return nil
}

func (x *ClientGameState) GetOtherPlayers() []*PlayerState {
	if x != nil {
		return x.OtherPlayers
	}
	return nil
}

func (x *ClientGameState) GetItems() [][]byte {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ClientGameState) GetDoors() []*DoorState {
	if x != nil {
		return x.Doors
	}
	return nil
}

func (x *ClientGameState) GetContainers() []*ContainerState {
	if x != nil {
		return x.Containers
	}
	return nil
}

// Player state
type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                             // Player ID (UUID as 16 bytes)
	EntityId      []byte                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // Entity ID (UUID as 16 bytes)
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`                 // Player username
	Position      *Position              `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`                 // Player position
	Direction     *PlayerDirection       `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`               // Player direction
	Inventory     []*ItemState           `protobuf:"bytes,6,rep,name=inventory,proto3" json:"inventory,omitempty"`               // Player inventory items
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_game_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_game_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_game_state_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerState) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PlayerState) GetEntityId() []byte {
	if x != nil {
		return x.EntityId
	}
	return nil
}

func (x *PlayerState) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerState) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlayerState) GetDirection() *PlayerDirection {
	if x != nil {
		return x.Direction
	}
	return nil
}

func (x *PlayerState) GetInventory() []*ItemState {
	if x != nil {
		return x.Inventory
	}
	return nil
}

// Position in 2D space
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_game_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_game_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_game_state_proto_rawDescGZIP(), []int{2}
}

func (x *Position) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Player direction and velocity
type PlayerDirection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vx            float64                `protobuf:"fixed64,1,opt,name=vx,proto3" json:"vx,omitempty"`       // Velocity X
	Vy            float64                `protobuf:"fixed64,2,opt,name=vy,proto3" json:"vy,omitempty"`       // Velocity Y
	Speed         float64                `protobuf:"fixed64,3,opt,name=speed,proto3" json:"speed,omitempty"` // Speed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerDirection) Reset() {
	*x = PlayerDirection{}
	mi := &file_game_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerDirection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDirection) ProtoMessage() {}

func (x *PlayerDirection) ProtoReflect() protoreflect.Message {
	mi := &file_game_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDirection.ProtoReflect.Descriptor instead.
func (*PlayerDirection) Descriptor() ([]byte, []int) {
	return file_game_state_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerDirection) GetVx() float64 {
	if x != nil {
		return x.Vx
	}
	return 0
}

func (x *PlayerDirection) GetVy() float64 {
	if x != nil {
		return x.Vy
	}
	return 0
}

func (x *PlayerDirection) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

// Door state
type DoorState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      []byte                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // Entity ID (UUID as 16 bytes)
	Position      *Position              `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	IsOpen        bool                   `protobuf:"varint,3,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoorState) Reset() {
	*x = DoorState{}
	mi := &file_game_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoorState) ProtoMessage() {}

func (x *DoorState) ProtoReflect() protoreflect.Message {
	mi := &file_game_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoorState.ProtoReflect.Descriptor instead.
func (*DoorState) Descriptor() ([]byte, []int) {
	return file_game_state_proto_rawDescGZIP(), []int{4}
}

func (x *DoorState) GetEntityId() []byte {
	if x != nil {
		return x.EntityId
	}
	return nil
}

func (x *DoorState) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *DoorState) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

// Item state with all possible fields
type ItemState struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ItemId   []byte                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`       // Item ID (UUID as 16 bytes)
	EntityId []byte                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // Entity ID (UUID as 16 bytes)
	Name     string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                         // Item name
	Quantity int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`                // Item quantity
	// Weapon fields
	AttackPower  int32   `protobuf:"varint,5,opt,name=attack_power,json=attackPower,proto3" json:"attack_power,omitempty"`
	Durability   int32   `protobuf:"varint,6,opt,name=durability,proto3" json:"durability,omitempty"`
	CriticalRate float32 `protobuf:"fixed32,7,opt,name=critical_rate,json=criticalRate,proto3" json:"critical_rate,omitempty"`
	WeaponType   string  `protobuf:"bytes,8,opt,name=weapon_type,json=weaponType,proto3" json:"weapon_type,omitempty"`
	// Armor fields
	DefenseRating int32  `protobuf:"varint,9,opt,name=defense_rating,json=defenseRating,proto3" json:"defense_rating,omitempty"`
	ArmorSlot     string `protobuf:"bytes,10,opt,name=armor_slot,json=armorSlot,proto3" json:"armor_slot,omitempty"`
	// Consumable fields
	HealingAmount int32 `protobuf:"varint,11,opt,name=healing_amount,json=healingAmount,proto3" json:"healing_amount,omitempty"`
	ManaAmount    int32 `protobuf:"varint,12,opt,name=mana_amount,json=manaAmount,proto3" json:"mana_amount,omitempty"`
	// Common field
	Description   string `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemState) Reset() {
	*x = ItemState{}
	mi := &file_game_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemState) ProtoMessage() {}

func (x *ItemState) ProtoReflect() protoreflect.Message {
	mi := &file_game_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemState.ProtoReflect.Descriptor instead.
func (*ItemState) Descriptor() ([]byte, []int) {
	return file_game_state_proto_rawDescGZIP(), []int{5}
}

func (x *ItemState) GetItemId() []byte {
	if x != nil {
		return x.ItemId
	}
	return nil
}

func (x *ItemState) GetEntityId() []byte {
	if x != nil {
		return x.EntityId
	}
	return nil
}

func (x *ItemState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemState) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ItemState) GetAttackPower() int32 {
	if x != nil {
		return x.AttackPower
	}
	return 0
}

func (x *ItemState) GetDurability() int32 {
	if x != nil {
		return x.Durability
	}
	return 0
}

func (x *ItemState) GetCriticalRate() float32 {
	if x != nil {
		return x.CriticalRate
	}
	return 0
}

func (x *ItemState) GetWeaponType() string {
	if x != nil {
		return x.WeaponType
	}
	return ""
}

func (x *ItemState) GetDefenseRating() int32 {
	if x != nil {
		return x.DefenseRating
	}
	return 0
}

func (x *ItemState) GetArmorSlot() string {
	if x != nil {
		return x.ArmorSlot
	}
	return ""
}

func (x *ItemState) GetHealingAmount() int32 {
	if x != nil {
		return x.HealingAmount
	}
	return 0
}

func (x *ItemState) GetManaAmount() int32 {
	if x != nil {
		return x.ManaAmount
	}
	return 0
}

func (x *ItemState) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Container state
type ContainerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   []byte                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"` // Container ID (UUID as 16 bytes)
	EntityId      []byte                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`          // Entity ID (UUID as 16 bytes)
	Position      *Position              `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`                          // Container position
	IsOpen        bool                   `protobuf:"varint,4,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`               // Is container open
	Items         []*ItemState           `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`                                // Items in container
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerState) Reset() {
	*x = ContainerState{}
	mi := &file_game_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerState) ProtoMessage() {}

func (x *ContainerState) ProtoReflect() protoreflect.Message {
	mi := &file_game_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerState.ProtoReflect.Descriptor instead.
func (*ContainerState) Descriptor() ([]byte, []int) {
	return file_game_state_proto_rawDescGZIP(), []int{6}
}

func (x *ContainerState) GetContainerId() []byte {
	if x != nil {
		return x.ContainerId
	}
	return nil
}

func (x *ContainerState) GetEntityId() []byte {
	if x != nil {
		return x.EntityId
	}
	return nil
}

func (x *ContainerState) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *ContainerState) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

func (x *ContainerState) GetItems() []*ItemState {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_game_state_proto protoreflect.FileDescriptor

const file_game_state_proto_rawDesc = "" +
	"\n" +
	"\x10game_state.proto\x12\x04game\"\x95\x02\n" +
	"\x0fClientGameState\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\fR\tsessionId\x128\n" +
	"\x0ecurrent_player\x18\x02 \x01(\v2\x11.game.PlayerStateR\rcurrentPlayer\x126\n" +
	"\rother_players\x18\x03 \x03(\v2\x11.game.PlayerStateR\fotherPlayers\x12\x14\n" +
	"\x05items\x18\x04 \x03(\fR\x05items\x12%\n" +
	"\x05doors\x18\x05 \x03(\v2\x0f.game.DoorStateR\x05doors\x124\n" +
	"\n" +
	"containers\x18\x06 \x03(\v2\x14.game.ContainerStateR\n" +
	"containers\"\xe6\x01\n" +
	"\vPlayerState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\fR\bentityId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12*\n" +
	"\bposition\x18\x04 \x01(\v2\x0e.game.PositionR\bposition\x123\n" +
	"\tdirection\x18\x05 \x01(\v2\x15.game.PlayerDirectionR\tdirection\x12-\n" +
	"\tinventory\x18\x06 \x03(\v2\x0f.game.ItemStateR\tinventory\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"G\n" +
	"\x0fPlayerDirection\x12\x0e\n" +
	"\x02vx\x18\x01 \x01(\x01R\x02vx\x12\x0e\n" +
	"\x02vy\x18\x02 \x01(\x01R\x02vy\x12\x14\n" +
	"\x05speed\x18\x03 \x01(\x01R\x05speed\"m\n" +
	"\tDoorState\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\fR\bentityId\x12*\n" +
	"\bposition\x18\x02 \x01(\v2\x0e.game.PositionR\bposition\x12\x17\n" +
	"\ais_open\x18\x03 \x01(\bR\x06isOpen\"\xaa\x03\n" +
	"\tItemState\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\fR\x06itemId\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\fR\bentityId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12!\n" +
	"\fattack_power\x18\x05 \x01(\x05R\vattackPower\x12\x1e\n" +
	"\n" +
	"durability\x18\x06 \x01(\x05R\n" +
	"durability\x12#\n" +
	"\rcritical_rate\x18\a \x01(\x02R\fcriticalRate\x12\x1f\n" +
	"\vweapon_type\x18\b \x01(\tR\n" +
	"weaponType\x12%\n" +
	"\x0edefense_rating\x18\t \x01(\x05R\rdefenseRating\x12\x1d\n" +
	"\n" +
	"armor_slot\x18\n" +
	" \x01(\tR\tarmorSlot\x12%\n" +
	"\x0ehealing_amount\x18\v \x01(\x05R\rhealingAmount\x12\x1f\n" +
	"\vmana_amount\x18\f \x01(\x05R\n" +
	"manaAmount\x12 \n" +
	"\vdescription\x18\r \x01(\tR\vdescription\"\xbc\x01\n" +
	"\x0eContainerState\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\fR\vcontainerId\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\fR\bentityId\x12*\n" +
	"\bposition\x18\x03 \x01(\v2\x0e.game.PositionR\bposition\x12\x17\n" +
	"\ais_open\x18\x04 \x01(\bR\x06isOpen\x12%\n" +
	"\x05items\x18\x05 \x03(\v2\x0f.game.ItemStateR\x05itemsBBZ@github.com/darkphotonKN/cosmic-void-server/game-service/proto/pbb\x06proto3"

var (
	file_game_state_proto_rawDescOnce sync.Once
	file_game_state_proto_rawDescData []byte
)

func file_game_state_proto_rawDescGZIP() []byte {
	file_game_state_proto_rawDescOnce.Do(func() {
		file_game_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_state_proto_rawDesc), len(file_game_state_proto_rawDesc)))
	})
	return file_game_state_proto_rawDescData
}

var file_game_state_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_game_state_proto_goTypes = []any{
	(*ClientGameState)(nil), // 0: game.ClientGameState
	(*PlayerState)(nil),     // 1: game.PlayerState
	(*Position)(nil),        // 2: game.Position
	(*PlayerDirection)(nil), // 3: game.PlayerDirection
	(*DoorState)(nil),       // 4: game.DoorState
	(*ItemState)(nil),       // 5: game.ItemState
	(*ContainerState)(nil),  // 6: game.ContainerState
}
var file_game_state_proto_depIdxs = []int32{
	1,  // 0: game.ClientGameState.current_player:type_name -> game.PlayerState
	1,  // 1: game.ClientGameState.other_players:type_name -> game.PlayerState
	4,  // 2: game.ClientGameState.doors:type_name -> game.DoorState
	6,  // 3: game.ClientGameState.containers:type_name -> game.ContainerState
	2,  // 4: game.PlayerState.position:type_name -> game.Position
	3,  // 5: game.PlayerState.direction:type_name -> game.PlayerDirection
	5,  // 6: game.PlayerState.inventory:type_name -> game.ItemState
	2,  // 7: game.DoorState.position:type_name -> game.Position
	2,  // 8: game.ContainerState.position:type_name -> game.Position
	5,  // 9: game.ContainerState.items:type_name -> game.ItemState
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_game_state_proto_init() }
func file_game_state_proto_init() {
	if File_game_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_state_proto_rawDesc), len(file_game_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_state_proto_goTypes,
		DependencyIndexes: file_game_state_proto_depIdxs,
		MessageInfos:      file_game_state_proto_msgTypes,
	}.Build()
	File_game_state_proto = out.File
	file_game_state_proto_goTypes = nil
	file_game_state_proto_depIdxs = nil
}
