apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    app: cosmic-void
    component: example-service
spec:
  type: ClusterIP
  selector:
    app: cosmic-void
    component: example-service
  ports:
  - name: grpc
    port: 7010
    targetPort: grpc
    protocol: TCP
